### ISSUE TITLE
StrictMode: TabContent uses componentWillReceiveProps

### ISSUE THREAD

**Issue by nickmccurdy** [reactstrap/reactstrap#1044]
### Issue description

- components: `TabContent`
- reactstrap version `6.0.1`
- import method `es` 
- react version `16.4.0`
- bootstrap version `4.1.1`

### What is happening?

TabContent uses componentWillReceiveProps.

### What should be happening?

componentWillReceiveProps should be replaced with getDerivedStateFromProps or UNSAFE_compnoentWillReceiveProps: https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops

### Steps to reproduce issue

Use `TabContent` in `<StrictMode>`.

### Error message in console

```
Warning: Unsafe lifecycle methods were found within a strict-mode tree:

componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: TabContent

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
```

**Comment by TheSharpieOne** [comment]
I think this will be a breaking change since we support react `16.0.0` and `getDerivedStateFromProps` is new in `16.3.0`. I don't think we can support both since we cannot remove `componentWillReceiveProps` unless `getDerivedStateFromProps` is supported, which means minimum version of `16.3.0` and we cannot leave it in there (AFAIK) without triggering that warning.

**Comment by nickmccurdy** [comment]
This is not a breaking change if you use [react-lifecycles-compat](https://www.npmjs.com/search?q=react-lifecycles-compat).

**Comment by illiteratewriter** [comment]
@TheSharpieOne want to add `react-lifecycles-compat`?

**Comment by TheSharpieOne** [comment]
Yeah, seems lightweight enough.
