### ISSUE TITLE
Feature: Close Tooltip when clicking outside of it (useful when high hide delay set)

### ISSUE THREAD

**Issue by juanmaguitar** [reactstrap/reactstrap#1079]
### Issue description

- components: `Tooltip`
- reactstrap version `6.1.0`

### What is happening?

If the Tooltip is set with some delay on hide, clicking outside doesn't close it
https://codesandbox.io/s/j3lp8k5np9

### What should be happening?

Clicking outside the tooltip should close it

**Comment by TheSharpieOne** [comment]
This is not how bootstrap has implemented it. In order to mimic bootstrap as much as possible, we cannot have it close when clicked outside.

bootstrap: https://codepen.io/TheSharpieOne/pen/pKpzBj

If you feel this is an issue, please raise it bootstrap. Once bootstrap changing it's implementation, reactstrap can do the same.

**Comment by juanmaguitar** [comment]
Opened the issue on bootstrap → https://github.com/twbs/bootstrap/issues/26719
