### ISSUE TITLE
How can I add an image to the Jumbotron?

### ISSUE THREAD

**Issue by Jatapiaro** [reactstrap/reactstrap#1130]
I have tried to override the css to
```
.jumbotron {
    background-image: requitre('./../../assets/images/index/jumbotron.jpg');
}
```

And also do the following:

```
                <Jumbotron style={{backgrounImage: JumbotronImage}} fluid>
                    <Container fluid>
                        <h1 className="display-3">Fluid jumbotron</h1>
                        <p className="lead">This is a modified jumbotron that occupies the entire horizontal space of its parent.</p>
                    </Container>
                </Jumbotron>
```

But nothing works, any ideas?

**Comment by TheSharpieOne** [comment]
That is specific to bootstrap styles and is outside of the domain of reactstrap. [Try this first to see if it helps](http://bfy.tw/J3fC), else I would ask on StackOverflow.

**Comment by philbgarner** [comment]
@Jatapiaro I had a similar issue and was able to solve it with the following code.

First, import your image normally:

`import bgimage from '../image_background.png'`

Then you can apply the style to your <Jumbotron> tag like so:

    <Jumbotron style={{ backgroundImage: `url(${bgimage})`, backgroundSize: 'cover' }}>

I thought it might be nice to put this here since this post shows up in Google results and the last comment is directing people to search Google...

**Comment by 3dxcode** [comment]
from flask:
### ### ### ****
