### ISSUE TITLE
popover dismiss

### ISSUE THREAD

**Issue by ashutoshsenger** [reactstrap/reactstrap#1131]
hello guys,
I'm using reactstrap popovers in my pop.js component.The issue which i'm facing is that when i'm clicking anywhere within the popover it is closing randomly.I doesn't want this type of behaviour.

**Comment by TheSharpieOne** [comment]
Hi @ashutoshsenger,
Good news, by default reactstrap's Popover component will **not** trigger the toggle method/callback when clicking within the popover.
Checkout these examples: https://reactstrap.github.io/components/popovers/

If you are placing the Popover _within_ the triggering element/button and if you are toggling `isOpen` yourself when that trigger/button is clicked, you may be closing the Popover inadvertently yourself. It's really hard to tell what is happening since you didn't follow the issue template and you didn't provide any code or link to see your code (via something like [stackblitz](https://stackblitz.com/edit/reactstrap-v6-gmzdxw?file=Example.js) or codesandbox)
