### ISSUE TITLE
Random strange flickers on modal components when stuff rendered above them

### ISSUE THREAD

**Issue by jeffersoneagley** [reactstrap/reactstrap#1134]
- components: `modal`
- reactstrap version `#6.3.0`
- import method `` 
- react version `#16.4.1`
- bootstrap version `#4.1.2`
- electron `#2.0.3`

### What is happening?

Random strange flickers on modal components:
![image](https://user-images.githubusercontent.com/15936010/42905480-0faa387a-8a8d-11e8-9675-f05e19842625.png)

![image](https://user-images.githubusercontent.com/15936010/42905808-f07e1790-8a8d-11e8-83c3-2559ff06a7e4.png)

### What should be happening?

The gray area on the modal shouldn't be affected by stuff rendering on top of it.

### Steps to reproduce issue

1. Set up a CRA app with reactstrap & react-toastify
2. Add a modal
3. Add a button to the modal and make it trigger a toast
4. Launch the app, trigger the modal, then trigger the toastify toast a couple times.
5. Observe crazy screen patterns possibly happen

note: I tried removing toast from the project, and the crazy flickering still happens to the OK button.

### Error message in console
No error messages found

### Code

I tried to recreate it here:
https://reactstrap-p5smmc.stackblitz.io
But can't seem to get it to show up.

**Comment by TheSharpieOne** [comment]
It looks like it's an issue with the rendering engine and since you mentioned electron and the stackbltiz link cannot reproduce it in the browser I assume it's only happening in electron. This issue may need to be raised there.

As a potential work-around, see if you can enable gpu acceleration (maybe by adding `transform: transale3d(0,0,0); ` to `.modal` in your custom styles. This would enable it in the browser, but I'm not sure how electron handles it).

**Comment by jeffersoneagley** [comment]
`.modal {
    transform: translate3d(0, 0, 0);
}`

Appears to have worked!
