### ISSUE TITLE
<DropdownItem> not working in Firefox and IE

### ISSUE THREAD

**Issue by gaurav3017** [reactstrap/reactstrap#1143]
```
<UncontrolledDropdown>
               <DropdownToggle nav caret>
                       <span>Availability</span>
                </DropdownToggle>
                <DropdownMenu>
                       <DropdownItem>
                                 <NavLink href="url">Backup current</NavLink>
                       </DropdownItem>
                       <DropdownItem>
                                  <NavLink href="url">Restore</NavLink>
                       </DropdownItem>
                       <DropdownItem>
                                  <NavLink href="url">Share</NavLink>
                       </DropdownItem>
                </DropdownMenu>
 </UncontrolledDropdown>
```
This is working fine in chrome but in Firefox and IE the DropdownItem/NavLink doesn't respond to mouse click event. Dropdown menu just closes on click and doesn't navigate to the "url".

**Comment by gaurav3017** [comment]
Works like charm. Thanks!

**Comment by ScottyMuffins** [comment]
Along the same lines of thinking as TheSharpieOne, if you want this to work with the React Router Dom `Link`, rather than nesting them in a `DropdownItem`, you can simply do something like this:

`<DropdownItem tag={Link} to='/Some-Example-Route' className='dropdown-option'>Some Example Route</DropdownItem>`

Thanks to TheSharpieOne for simplifying the explanation.
