### ISSUE TITLE
Modal background black

### ISSUE THREAD

**Issue by QiWang19** [reactstrap/reactstrap#1151]
### Issue description

- components: `Modal`
- reactstrap version `"reactstrap": "^6.2.0"`
- react version `"react": "16.0.0"`
- bootstrap version `"bootstrap": "^4.1.1"`

### What is happening?

I copied this Modals without Fade Effect into my project https://reactstrap.github.io/components/modals/ . But when I click the button the background turned black, no transparent.
I think maybe something wrong with my bootstrap version. After ```npm ls bootstrap```

```bash
├── bootstrap@4.1.3
└─┬ patternfly@3.53.0
  ├── bootstrap@3.3.7
  ├─┬ eonasdan-bootstrap-datetimepicker@4.17.47
  │ └── bootstrap@3.3.7  deduped
  └─┬ patternfly-bootstrap-treeview@2.1.5
    └── bootstrap@3.3.7  deduped
```
### What should be happening?
I want the background changes the same as your example.
What should I do ?

**Comment by TheSharpieOne** [comment]
Since you have both v3 and v4 of bootstrap, it really depends on how you are importing/including bootstrap into your project. You need to make sure that bootstrap v4 is used and not v3. If another dependency is bringing in bootstrap v3, you might need to remove the dependency or upgrade it (or open an issue with the repo to support bootstrap v4)
