### ISSUE TITLE
UncontrolledCarousel and Carousel's autoPlay doesn't work

### ISSUE THREAD

**Issue by wpliao1989** [reactstrap/reactstrap#1224]
- components: `UncontrolledCarousel`, `Carousel`
- reactstrap version `#6.4.0`
- import method `es`
- react version `#16.5.1`
- bootstrap version `#4.1.3`

### What is happening?

The component's `autoPlay` prop doesn't work. When set to false, it still auto plays.
After some investigation I tracked it down to this line in `Carousel`: https://github.com/reactstrap/reactstrap/blob/6.4.0/src/Carousel.js#L57 which gets executed in `componentWillReceiveProps`. The issue with this is that `componentWillReceiveProps` can be called with a number of reasons https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops. When it's called, the component starts auto play even if `autoPlay` is false.

### What should be happening?

It should take `autoPlay` into account.

### Steps to reproduce issue

1. Start the example app
2. Render `<UncontrolledCarousel autoPlay={false} />`

### Code

https://reactstrap-8mqjbr.stackblitz.io

**Comment by TheSharpieOne** [comment]
This is due to bootstrap's confusing options for carousel: https://getbootstrap.com/docs/4.1/components/carousel/#options

`autoPlay` is "should the carousel automatically cycle **on load**", it doesn't prevent the carousel from automatically cycling completely. After the user interacts with the carousel (such as hovering over it) it should starting automatic cycling even if `autoPlay` is `false`.

If you don't want it to automatically cycle, you have to define `interval` as `false`. This is the same for bootstrap itself.

It is done this way for bootstrap compatibility.

**Comment by wpliao1989** [comment]
I see! Thanks for the awesome explanation! I will close this issue.
