### ISSUE TITLE
conditional modal footer closes modal

### ISSUE THREAD

**Issue by edgji** [reactstrap/reactstrap#126]
Is there a way to conditionally display/toggle the modal footer without causing the modal to close?

My use case establishes the modal footer as conditional when there are files selected i.e I display buttons to remove files. I'm running into the issue that while I can make the modal footer conditionally appear, the case in which the footer should disappear causes the entire modal to close.

Take a look at the following bin sample, toggle the modal and add a file. When you remove files the entire modal closes.
http://www.webpackbin.com/NkyVH5_jb

**Comment by TheSharpieOne** [comment]
Figured it out... (took longer to figure out how to edit the webpackbin (my browser window was too small (less than 1280px wide) and I didn't realize the prevented me from editing and doing things...)
The button is removed from the DOM when there are no more files and [this line](https://github.com/reactstrap/reactstrap/blob/5f60168ea868892b021b83b7a0db9aa47fb98d6e/src/Modal.js#L75) states that if the thing that was clicked is not within the modal to go ahead and close it. Thus, anytime something is clicked in a modal and it triggers it to be removed from the modal, the modal will close.

A possible fix would be to set `useCapture` to `true` instead of `false` on the [`addEventListener`](https://github.com/reactstrap/reactstrap/blob/5f60168ea868892b021b83b7a0db9aa47fb98d6e/src/Modal.js#L118). This should allow the modal to capture the event on the way up, before it triggers other handlers. I'll check this out when I get a chance to see if it works the way I think it will.

For now, a workaround would be to use styles to hide and show the remove button instead of adding it and removing it from the DOM.

**Comment by TheSharpieOne** [comment]
Looks like it fixes the issue, tested locally. A PR is up for review.

**Comment by eddywashere** [comment]
Fix published in 3.0.1

**Comment by edgji** [comment]
awesome! thanks @TheSharpieOne Your fix and thorough response actually made me lookup more info on event bubbling and capturing.
