### ISSUE TITLE
Forms documentation component is broken. [out of scope]

### ISSUE THREAD

**Issue by unfaceit** [reactstrap/reactstrap#1332]
- components: `Form`
- documentation website

### What is happening?

In your documentation, when you go to [https://reactstrap.github.io/components/form/](FORM), your react application breaks. Page reload to a different tab required, to make it render again. 

### What should be happening?

We should be able to access FORM component documentation.

### Steps to reproduce issue

1. Go to your docs - [https://reactstrap.github.io/components/alerts/](url)
2. Click on **Form**

### Error message in console

```
Error: Minified React error #137; 
```

**Comment by bwanicur** [comment]
When I try to run `npm start` locally, I get the following error:

` ERROR in Invariant Violation: input is a void element tag and must neither have 'children' nor use 'dangerouslySetInnerHTML'.`.

I'm new to webpack and I could not get a meaningful stack trace, or I would post it.

**Comment by Xachman** [comment]
https://github.com/Xachman/reactstrap/commit/11d9f1a68a90e02f6f7c15de7fc1b2adb7113e75

The issue is with the plaintext attribute.  I dont have time to write a unit test for this right now so I cannot create a PR for this change now.  But if you are working locally and would like to read the docs you can either remove the plaintext input or use this update.
