### ISSUE TITLE
Missing default export since 7.0.0 release

### ISSUE THREAD

**Issue by gvautour** [reactstrap/reactstrap#1343]
- reactstrap version `#7.0.0`
- react version `#16.7.0`
- bootstrap version `#4.2.1`

Failed to compile
./node_modules/reactstrap/dist/reactstrap.es.js
Attempted import error: 'react-lifecycles-compat' does not contain a default export (imported as 'reactLifecyclesCompat').

**Comment by king-kay** [comment]
@gvautour I just noticed this too. Apparently it's just an imports mistake with the 7.0.0 release.

#### Reason
On this line: ```import reactLifecyclesCompat, { polyfill } from 'react-lifecycles-compat';``` in "dist/reactstrap.es.js", ```reactLifecyclesCompat``` is imported as a default export and the **reactLifecyclesCompat** package doesn't define a default export, instead, it only exports ```polyfill```. Hence the reason for the error. 

#### Potential Fix
A possible fix would be to remove the ```reactLifecyclesCompat``` part completely, since the **react-lifecycles-compat** module **doesn't expose a default export**, and update the ```reactLifecyclesCompat.polyfill``` reference (somewhere on line (2300) with ```polyfill```. 

So, in the end: 
--  ```import reactLifecyclesCompat, { polyfill } from 'react-lifecycles-compat';``` 
++```import { polyfill } from 'react-lifecycles-compat';```

...

-- ``` var _default = (0, reactLifecyclesCompat.polyfill)(Transition);```
++ ```  var _default = (0, polyfill)(Transition);```

And voilà, problem solved! I could send a PR if that's okay.

**Comment by king-kay** [comment]
So, I took a closer look at the issue and I realized I was looking at it all wrong! The files I referenced in my previous comment were in the ```dist``` directory (which is generated by rollup), silly me. On closer look, the offending line is not even from any of the components in reactstrap - it's from ```Transition``` in  the react-transition-group package which rollup apparently bundles. The cjs build doesn't seem to have this import problem though, just the ejs one.

**Comment by ramennoodles20** [comment]
@king-kay I've been looking all over the internet for an fix like this one. Thank you!

**Comment by raitucarp** [comment]
What is the status of this issue? Can someone fix and send PR for this issue?

**Comment by king-kay** [comment]
@raitucarp I'll try to find the root cause of the bug today (I suspect rollup) and probably send a PR when I finish working on it. Since it's just a wrong import, it shouldn't be too hard to fix.

**Comment by indatawetrust** [comment]
version 6.5.0 is currently running

**Comment by king-kay** [comment]
@TheSharpieOne, So, I cloned the source and created a fresh build (```yarn build```) and surprisingly, the generated ```reactstrap.es.js``` file in the ```dist``` directory has the following line:
 
![image](https://user-images.githubusercontent.com/20065279/50557816-13c37280-0ce9-11e9-9ec6-9004219cc648.png)

instead of this (which you'll get when you install reactstrap v7.0.0 using npm or yarn):

![image](https://user-images.githubusercontent.com/20065279/50557872-7a489080-0ce9-11e9-905e-531d0b5b0857.png)

Also, I noticed that the local build I have also lacks this line 

![image](https://user-images.githubusercontent.com/20065279/50557903-d7444680-0ce9-11e9-8847-cb620540206e.png)

Instead, it directly sets the ```exports.default``` to ```Transition``` without wrapping it with the ```polyfill```. Like so: 

![image](https://user-images.githubusercontent.com/20065279/50558084-4ec6a580-0ceb-11e9-9e0f-a7e50687b6b4.png)

I then packed the local copy with ```yarn pack``` and installed it in a demo create-react-app and everything works just fine!

@TheSharpieOne what do you think?

**Comment by king-kay** [comment]
@TheSharpieOne  I think I know what the issue is now! After much digging, I turns out that the version of  **react-transition-group** referenced in the ```package.json```  of the project (v2.3.1) and the one actually used to build the release (v2.5.2) are different. How I can tell is, **react-transition-group** v2.3.1 didn't even have **react-lifecycles-compat** as a dependency whereas the v2.5.2 does. I got the same issue when I built using the v2.5.2 of  **react-transition-group**. A possible solution to this would be to rebuild the 7.0.0 release using the v2.3.1 of **react-transition-group** (and increment the patch). But if we were to bump the dep. version later, we would still run into the same issue. I think I have a theory as to why the v2.5.2 of **react-transition-group**  doesn't work with reactstrap. I haven't confirmed it yet though that's why I won't say it now.

I hope this helps!

**Comment by TheSharpieOne** [comment]
I'm working on fixing this. I have upgraded rollup as well as webpack (for the docs) and all of the babel stuff to the latest... it still an issue.
Thinking more about it... react-transition-group _shouldn't_ be in the es.js, it should be getting imported. The fact that it is not imported is a bug and probably the root cause.
I think the import being `import Transition from 'react-transition-group/Transition'` is the problem. When I made it just `import { Transition } from 'react-transition-group'` it fixed it... but I think the import was like that for another reason.

**Comment by TheSharpieOne** [comment]
I reworked the build for 7.0.1, everything looked good, let me know if it works or not.

**Comment by king-kay** [comment]
I'll give it a try once the new year's celebrations die down a bit. Thanks @TheSharpieOne!

**Comment by flipchart** [comment]
@TheSharpieOne working for me now. Thanks!
