### ISSUE TITLE
Tooltip transitions not working

### ISSUE THREAD

**Issue by ghidosoft** [reactstrap/reactstrap#1370]
- components: `Tooltips`
- reactstrap version `#7.1.0`
- import method `es`
- react version `#16.7.0`
- bootstrap version `#4.2.1`

### What is happening?

Tooltips appears in the right position but without fade in/out transitions.

### What should be happening?

Should apply transitions as per samples https://reactstrap.github.io/components/tooltips/

### Steps to reproduce issue

1. Install `reactstrap` as per instructions https://www.npmjs.com/package/reactstrap#adding-bootstrap
2. Add `react-popper` and `react-transition-group` libraries
3. Add an `<UncontrolledToolip>xxx</UncontrolledTooltip>` component
4. No transitions

### Error message in console

No error messages.

### Code

https://codesandbox.io/s/01zm5k5w10

**Comment by TheSharpieOne** [comment]
This is because docs reflect what is in master and not a release. The transitions have not been released yet.

I would love to get to the point where we have multiple versions of the docs showing released version and allowing users to selects which version they need docs for (similar to bootstrap's docs).

Overhauling the docs is something needed, but it's a larger task and often a moving target.

**Comment by ghidosoft** [comment]
Ah OK, if that's the case I can close this ticket and wait for the next release.

Thank you.
