### ISSUE TITLE
TabContent vs TabPane

### ISSUE THREAD

**Issue by ridhwaans** [reactstrap/reactstrap#1406]
I went over the docs and dont quite understand what the difference between tabcontent and tabpane is. Is TabContent a single container to hold all Tabpanes, and Tabpane a div itself? Then why is `<TabContent activeTab={this.state.activeTab}>` in the examples

**Comment by GoPro16** [comment]
`TabContent` is a context container for the `TabPane`. It makes it easier to conditionally show which tab when its active rather than having to conditionally check if the `activeTab == tabId` in some HOC.

If you see the below link to the `TabPane` its just grabbing the `activeTabId` context from the `TabContent` component in order to hide itself if the tabIds are not equal.

https://github.com/reactstrap/reactstrap/blob/master/src/TabPane.js#L18
