### ISSUE TITLE
UI with production build looks different from development build

### ISSUE THREAD

**Issue by pula2000** [reactstrap/reactstrap#1416]
I'm using reactstrap components like Container, etc. When previewing the UI in development mode,
the text size seems smaller compared to production build. Container dimensions also seem to be smaller in production build compared to development build. Can someone explain why the UI would look different in production build vs development build?

**Comment by virgofx** [comment]
That has not been the case for anyone else and would be a major issue. You'll need to provide more details or create a codesandbox/fiddle showing side by side differences.

**Comment by TheSharpieOne** [comment]
Make sure you're not zoomed on either of your sites.

Also, depending on your build for each environment, the CSS order can be different. Since the order of CSS is important with things on the same specificity, the order can affect the styles. I personally have seen styles change in production build due to the build tool using a different delivery method between dev and prod (such as style loader and css extractor).

**Comment by pula2000** [comment]
At the project level there were a lot of react build issues and misconfiguration with my spring boot+react project. I fixed them and the issue went away.
