### ISSUE TITLE
Input element don't work properly with ref's!

### ISSUE THREAD

**Issue by DuudeXX8** [reactstrap/reactstrap#1451]
### Hi everyone.I'm struggling almost 4 days dear developers of reactstrap BECAUSE OF YOU 😡😡😡! And today I understand that's your'e `<Input />` element not working properly.

- components: `Input`
- reactstrap version `7.1.0`
- import method `es` 
- react version `16.8.6`
- bootstrap version `4.0.0-alpha`

### Demonstrating the problem: 😐

You have a trivial form.Which have a onSubmit event.Which have a REACTSTRAP Input element.And if you try to get value of this element via ref's.This doesn't work!Console show's `undefined bro`.😒😒😒

This is your'e form!
```
<Form onSubmit={this._onSubmit}>
         <Label for="name">Name</Label>
         <Input ref={this.nameRef} type="text"  name="name" id="name" placeholder="Name"/>
      <Button color="success">Submit</Button>
</Form>
```

This is your'e dummy function which work's with your'e dummy FORM.
```
_onSubmit = (e) => { 
        console.log(this.nameRef.current.value);
        e.preventDefault();
};
```

### If you change this reactstrap `Input` to default jsx `input` that's work correct and you can get what you want.

###HERE THE PROVE 

https://stackblitz.com/edit/reactstrap-jzfbx9?file=Example.js

I hope you will fix this issue because I love Reactstrap 😔

**Comment by TheSharpieOne** [comment]
`ref` will get you a reference to the `Input` component. Use `innerRef` to get a reference to the underlying `input`.

It's not super clear because of the style in which the docs define/explain the available props, but it says:

```
  // innerRef would be referenced to select node or input DOM node, depends on type property
  innerRef: PropTypes.oneOfType([
    PropTypes.object,
    PropTypes.string,
    PropTypes.func,
  ])
```

https://stackblitz.com/edit/reactstrap-pcngs4?file=Example.js

The reason it is this way is because this is how react originally worked. I say originally because now there is `forwardRef` which allows a component to actual obtain the ref prop and forward it to the underlaying component. Before `forwardRef` there was no way to get access to that `ref` prop, so another prop was used, `innerRef` in this case. There is a PR to implement `forwardRef`, but it's still a work in progress.

**Comment by DuudeXX8** [comment]
@TheSharpieOne  Actually innerRef is not a standard React property but I use it until you will fix this ref issue.Thank you :)

**Comment by TheSharpieOne** [comment]
`innerRef` is not standard, but it is extremely common; a de facto standard.
Again, `ref` is a standard for getting a reference to the component you place it on, in this case you are placing it on `Input` and will get a reference to `Input`.

**Comment by TimNZ** [comment]
@TheSharpieOne I just experienced this and had to explore Input src to see why focus() was doing nothing.   

 Input.ref is never set as getRef is never referenced/called.
So this.ref check fails in focus()
