### ISSUE TITLE
Install specific components

### ISSUE THREAD

**Issue by dhope-nagesh** [reactstrap/reactstrap#1492]
Is there any way to install few components rather than installing entire reactstrap package via npm?

**Comment by TheSharpieOne** [comment]
The components are individually exported in a way that modern tree shaking can automatically remove unused components/code. You can also import via `import Alert from 'reactstrap/src/Alert'` or `import Alert from 'reactstrap/lib/Alert'` (depending if your build supports the src syntax or not).
This means your bundle will have the few component you use (and not all of the components). As for installing specific components like lodash does (note: lodash does this because tree shaking doesn't always work that great for its package), no, the package from npm has everything.

Here are more stats about the reactstrap npm package and impacts: https://bundlephobia.com/result?p=reactstrap@8.0.0

**Comment by dhope-nagesh** [comment]
@TheSharpieOne Thanks for your inputs, this solve the issue
