### ISSUE TITLE
Input type select losing default values after rerender (loading server side data)

### ISSUE THREAD

**Issue by bhimubgm** [reactstrap/reactstrap#1501]
### Issue description

- components: `Input`
- reactstrap version `#^8.0.0`
- react version `#^16.8.6`
- bootstrap version `^4.3.1`

### What is happening?

Select options are loaded from remote API. The input field doesn't retain the default values after the options are loaded from rest api.

### What should be happening?
Default values should be pre-selected even after component rerenders on state change.

"Loading Options" is shown while data from API are being fetched. Once data from API are retained, component rerenders and default values are pre-selected.

**Comment by hoslersk** [comment]
Could you provide some additional details here on how the options and default selections are tracked/managed and then rendered via a snippet?

May be unrelated, but worth noting that React docs recommend using a `value` prop on `select` elements as opposed to explicit use of the `selected` attribute on the nested `option`s.

Link for reference: https://reactjs.org/docs/forms.html#the-select-tag

**Comment by bhimubgm** [comment]
I was using "defaultValue" attribute.
`<Input
          type="select"
          defaultValue={this.getValue()}
          ...
        >
          {options}
        </Input>
`

I was able to solve it by using "value" instead of "defaultValue" attribute. (Controlled Component)
`<Input
          type="select"
          value={this.getValue()}
          ...
        >
          {options}
        </Input>
`

**Comment by hoslersk** [comment]
Ah, okay. That would do it. You can use both `defaultValue` (value for initial load) and `value` (dynamic value), but I think `value` is definitely the minimum requirement. Can this issue be closed?

**Comment by hoslersk** [comment]
Just confirming that this is related to JSX usage and not the fault of Reactstrap (and should therefore be closed). The `Input` component is basically a combination of the `input`, `select`, and `textarea` form elements to make usage and styling easier for a developer. Besides a few props that determine how an input-like element should look what type of element to use (like `type` or `tag`), this component is a relatively basic layer of abstraction over these standard elements (for flexible use). That being the case, you can test by simply replacing `Input` in your JSX with `select` to determine if this issue is with the Reactstrap component or with JSX usage.

**Comment by bhimubgm** [comment]
@hoslersk: Yes, This is the default behavior of select field in react with` defaultValue` (`Controlled and Uncontrolled Components`). It has nothing to do with Reactstrap. We may close this thread.

**Comment by ammaraamir39** [comment]
@hoslersk You cannot change the value attribute if you want it, as an openhanded field . The results do not change on the screen while typing

**Comment by Sameer447** [comment]
I think you can use defaultInputValue attribute instead value and defaultValue
