### ISSUE TITLE
UncontrolledCarousel should not use src of an item as key

### ISSUE THREAD

**Issue by christopheblin** [reactstrap/reactstrap#1536]
If you want to use the same image in 2 different slides, you have a react warning :

    Warning: Encountered two children with the same key, `https://xxx.png`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.

The problem lies in https://github.com/reactstrap/reactstrap/blob/master/src/UncontrolledCarousel.js#L67

Here, the key is defined to be img.src

I suggest to use the index in the array as the key (which could be the second param of the map function on line 62)

My current workaround is to copy / paste the entire UncontrolledCarousel call to change that.

**Comment by GoPro16** [comment]
`react` doesn't recommend using array indexes as the keys for the items. I would suggest adding another property to the `items` array `prop-types` called `key` or `id`.

`key={item.key || item.src}`

**Comment by baktiaditya** [comment]
@GoPro16 hi, please kindly check #1650. I think is quite save to define key like that, thus user doesn't have to put `key` when declaring `items` array.

**Comment by TheSharpieOne** [comment]
> I think is quite safe to define key like that
It is not safe. The index will change as the array changes (when adding and removing items not at the end of the array). This will cause react to think the components are different and it will unmount the "old" and initialize and mount a "new" component (even thought it's the same component). Things like state would be lost, all because the item was shifted within the array.

**Comment by baktiaditya** [comment]
@TheSharpieOne updated.
