### ISSUE TITLE
Tests run out of memory

### ISSUE THREAD

**Issue by eddywashere** [reactstrap/reactstrap#154]
Watch task is basically dead at the moment. Noticed that this issue is happening way more often then it used to. @TheSharpieOne mentioned moving off of karma all together and I am +1000 to that. Keeping this issue open to track the status of it. 

also, I had some experiment with enzyme and jest in https://github.com/reactstrap/component-template and was pleasantly surprised by the watch, coverage and just general experience of using it.

**Comment by TheSharpieOne** [comment]
I went with Jest and react-scripts test since it is more inline with what the component-template project is doing... and also because it was less work since Jest officially supports jasmine's API (meaning the tests didn't have to change)... but travis is taking it's sweet time running the tests. Each suite seems to be taking forever:
![image](https://cloud.githubusercontent.com/assets/664714/18847955/306e215c-83fa-11e6-9621-c5df496f4cd8.png)
`422 tests passed (422 total in 63 test suites, run time 147.024s)`
Compare that to mocha in a similar project with coverage `493 passing (1s)` Converting to mocha is more effort, but may be desired in the long run.
