### ISSUE TITLE
Failed prop type isRequired on Modal 

### ISSUE THREAD

**Issue by wambugudavis** [reactstrap/reactstrap#1541]
### Issue description

- components: `Modal`
- reactstrap version `#8.0.0`
- import method `npm`
- react version `#16.8.6`
- bootstrap version `#4.0.0`

### What is happening?

I noticed a warning on the console which was not present previously. It appears immediately when the Modal component is mounted. I can't seem to find the prop listed anywhere on the docs. The modal still works correctly. 

### Error message in console

```
Warning: Failed prop type: Cannot read property 'isRequired' of undefined
    in Modal (at CustomModal.js:117)
```

### Code
`  
<Modal
      isOpen={this.props.modal.show}
      toggle={this.toggle}>
      ...
 </Modal>`

**Comment by virgofx** [comment]
Looks like an issue with your code --- `CustomModal.js` line 117.

**Comment by wambugudavis** [comment]
That's the line where the Modal component is used. I've used it as shown above

**Comment by TheSharpieOne** [comment]
Here are the prop types for modal. None of them are `.isRequired`. Some of them are imported from react-transition-group and react-transition-group does have some required props. Maybe the issue is stemming from react-transition-group's props?

https://github.com/reactstrap/reactstrap/blob/315bb00b31790e2046e2ac9b10e03abf3e35f199/src/Modal.js#L20-L60
