### ISSUE TITLE
Does Collapse render Children when isOpen === false?

### ISSUE THREAD

**Issue by awitherow** [reactstrap/reactstrap#1608]
Just thinking about performance and such 👍

**Comment by TheSharpieOne** [comment]
Yes, it still renders the children. This is mostly because when though `isOpen` is `false`, while it is animating it is still visible. You can use the transition callbacks to have your component not render any children within Collapse when the animation is completed.
Why do we render the children when they are not shown? This is how bootstrap itself works and it preserves the state of the components within the collapse.
If you want to not preserve the state of the components, add a `key` which changes every time the collapse is toggled open.
If you are looking for a performance boost, you can simply have the children be another component which only updates when its props change.

**Comment by awitherow** [comment]
So if they are already prerendered, going to isOpen = true will not need to rerender the children? Nice. Thank you for educating me :D
