### ISSUE TITLE
Popover left placement doesn't work correctly

### ISSUE THREAD

**Issue by luigidarco96** [reactstrap/reactstrap#1613]
### Issue description

- components: 'popover'
- reactstrap version `7.1.0`
- react version `16.8.6`
- bootstrap version `4.3.1`

### What is happening?
If I set the popover placement to left it will show on the right.

I encountered this issue also in the reactstrap demo.

### Code
<Popover
                className="header-popover-width"
                isOpen={true}
                target={"first-button"}
                placement={"left"}
                toggle={this.props.toggle}
                trigger="block"
>

**Comment by TheSharpieOne** [comment]
The issue with the docs is due to the column in which the popover appears. The column is not wide enough (and has overflow set to scroll) to show the popover to the left, so it will automatically flip the popover.
I suspect your popover similarly does not have enough room to display and is flipping. You can set `flip` to `false` to disable the automatic flipping.

For our docs, we should probably move center the buttons within the column so that all of the difference placements works.
