### ISSUE TITLE
Class 'modal-open' is persisted on body even when the Modal component is unmounted

### ISSUE THREAD

**Issue by CugeDe** [reactstrap/reactstrap#1626]
### Issue description

- components: `Modal`
- reactstrap version `#8.0.1`
- react version `#16.9.0`
- bootstrap version `#4.3`

### What is happening?

Class 'modal-open' is persisted on body even when the Modal component is unmounted.
I think this happens because the modal is not displayed entirely and unmounted.

### What should be happening?

Class 'modal-open' should be removed of the body when the Modal component is unmounted.

### Steps to reproduce issue

Instanciate a modal with `isOpen=true` by default, unmount the component before it was even displayed. (see #code)

### Error message in console

No error message.

### Code

https://codesandbox.io/embed/buggy-modal-vnyml

**Comment by javierfvargas** [comment]
Hi all,  I know this issue has been closed for a while however I must report the fix you proposed is problematic in other scenarios.  You decided at some point to fallback to call the close function depending only on the props "isOpen" instead of the state of the modal itself.   

It effectively solves the problem in the example above, however I noticed that for example if once the modal is accepted you change the external state to turn it closed and in a very short interval something happens that triggers the destroy of the modal (e.g, a push to other route, or a change in other states that causes the modal not to be rendered such us unmounting its parent element), the react optimizer accumulates all those changes and when it is time for the modal to destroy its props is in false yet the "modal-open" class is never removed unless you introduce some kind of delay or you simple doesn't close the modal an relay on it being destroyed when the dom changes.

The point is that only the modal knows when it changed the DOM to include the class "modal-open" yet you relay on an external variable to decide whether or not remove the class and the scroll is affected.
