### ISSUE TITLE
Bootstrap 4.4 responsive containers

### ISSUE THREAD

**Issue by kyletsang** [reactstrap/reactstrap#1721]
- components: `Container`
- bootstrap version `4.4.1`

Bootstrap 4.4 has added responsive containers:
https://getbootstrap.com/docs/4.4/layout/overview/#containers

Examples:
https://getbootstrap.com/docs/4.4/examples/grid/#containers

I can probably tackle this, but will need a bit of input.  Currently the `Container` component has one prop `fluid` which is a boolean.  For this feature would it be better to create a new props (`size`) where you can set the size breakpoint?

Example:
```
<Container size="fluid" />
<Container size="xl" />
<Container size="sm" />
```

**Comment by TheSharpieOne** [comment]
It would be best to be backwards compatible and avoid a breaking change. That said, we could support both `size` and `fluid` (if `fluid` is `true`, it would force the same as `size="fluid"` regardless of the value of `size`)

Or, we can use `fluid` like `fluid="md"` indicating that at the `md` breakpoint the container would become fluid (which is what the new styles seem to do). It would keep a single prop, and be backwards compatible since `fluid={true}` would work the same.

I kinda like the second way. I know we use `size` elsewhere, but that is more about setting a size regardless of breakpoints and not an actual breakpoint.

**Comment by kyletsang** [comment]
Ok that makes sense.

For the fluid behavior, the size breakpoint actually indicates the container would be fluid up to the breakpoint, then would behave as a regular container on that breakpoint and after.  For example, `fluid="md"` would mean `xs`, `sm` would be fluid, and `md`, `lg`, `xl` would be regular sized.

That being said, would `fluid="md"` still be the best convention?  If you're ok with this, I will implement the changes.

**Comment by TheSharpieOne** [comment]
That is a good point, but I still kind of like it. I was trying to think of what the prop would be based on the value and how/when it affect the width. Maybe `max` or `maxWidth`, but then setting `true` there doesn't make sense.

**Comment by kyletsang** [comment]
Sounds good.  Will go with `fluid="breakpoint"` for the PR.
