### ISSUE TITLE
CSS Loading

### ISSUE THREAD

**Issue by yussinsharp** [reactstrap/reactstrap#173]
What is the recommended process for adding the bootstrap css to a React application? It seems like the Button component relies on global classes like `btn` to inherit its style. So currently I am pasting the CDN link directly into the page but is there a better way through node modules and ES6 `import`. I have noticed other projects do `import 'bootstrap-css';` at the top of their app.jsx files. Is this a package I need to add to my package.json? Documentation on this topic would be much appreciated, unless I am blind and have not been able to uncover it!

**Comment by eddywashere** [comment]
I've been meaning to add a proper getting started section that uses create-react-app to demo reactstrap setup and offer a few suggestions around pulling in external bootstrap css. 

For now, here's what I've got:

---

### Including Bootstrap CSS

Include a stylesheet link at the top of your page to easily include the Bootstrap 4 CSS.

```
<link rel="stylesheet" href="https://unpkg.com/bootstrap@4.0.0-alpha.4/dist/css/bootstrap.min.css">
```

Otherwise, if your build tooling supports importing css, you could install bootstrap from npm: 

```
npm install bootstrap@4.0.0-alpha.4 --save
```

An example can be found in [reactstrap/component-template](https://github.com/reactstrap/component-template). See the imported the dist css [here (example)](https://github.com/reactstrap/component-template/blob/bd2b3c305318fd627771ee283281c1b07965816a/src/docs/index.js#L8).

If you want more control over bootstrap (ex: theming), you could use webpack and something like [sass-loader](https://github.com/jtangelder/sass-loader). With that, you can import what you need from bootstrap source `.scss` files and change variables/mixins as you please.

**Comment by yussinsharp** [comment]
That's awesome! Thanks for this. I have sass loading implemented so will see where I get with that.
