### ISSUE TITLE
Popover schedule update

### ISSUE THREAD

**Issue by sho-87** [reactstrap/reactstrap#1744]
I have a div component that is being panned/zoomed, and the popover associated with it becomes incorrectly positioned after any transformation. What is the correct way to manually call `scheduleUpdate` on those components?

**Comment by kevinstadler** [comment]
Related to #1737 (only your issue is about the Popover's `target` component resizing, and not the Popover's *content*, right?). Either way it seems like reactstrap does not pass Popper's `scheduleUpdate` method down to the Popover component, which would be one option how to address both this issue and #1737.
