### ISSUE TITLE
8.2.0 -> 8.3.x was a breaking change

### ISSUE THREAD

**Issue by k-funk** [reactstrap/reactstrap#1758]
- components: `DropdownToggle`, `DropdownItem`, `DropdownMenu`
- reactstrap version `#8.3.1`
- import method `es`
- react version `#16.12.0`
- bootstrap version `#4.4.1`

I've got two issues:
1. My snapshots changed due to `<ForwardRef />`
2. I can't `extend` from `DropdownItem` (it may not be the only class that has this problem)

#### In browser error:
```
Uncaught TypeError: Super expression must either be null or a function
```

#### In jest tests error:

Snapshots failing:
```
    -       </DropdownToggle>
    -       <DropdownMenu
    -         flip={true}
    -         tag="div"
    -       >
    -         <DropdownItem
    +       </ForwardRef>
    +       <ForwardRef>
    +         <ForwardRef
```

Runtime Error:
```
TypeError: Class extends value #<Object> is not a constructor or null
```

### Code

```
import { DropdownItem } from 'reactstrap';
export class PopoverMenuItem extends DropdownItem {}
```

I *think*, that https://github.com/reactstrap/reactstrap/commit/64847df4a858c4ad7fc4c0f876fcff9a456ee55b caused this issue.

**Comment by TheSharpieOne** [comment]
I understand your concern, but please take note of the following:

1. `My snapshots changed due to <ForwardRef />`
Your snapshot was testing reactstrap's implementation which is not a good test. You should only test the things you create and not the third-party libraries. While reactstrap's implementation did change, the input (props and what the do) as well as the output (actual HTML rendered) didn't change. You can mock out reactstrap components and your snapshots will ensure that you pass the same props to the same (mocked) component. When reactstrap's implementation changes, your tests will pass.

Or you can just update your snapshots: (source [jest docs on snapshot testing](https://jestjs.io/docs/en/snapshot-testing))
>The snapshot artifact should be committed alongside code changes, and reviewed as part of your code review process. Jest uses pretty-format to make snapshots human-readable during code review. On subsequent test runs Jest will compare the rendered output with the previous snapshot. If they match, the test will pass. If they don't match, either the test runner found a bug in your code (in this case, it's <Link> component) that should be fixed, **or the implementation has changed and the snapshot needs to be updated.**

2. Inheritance/extending is not officially supported by reactstrap (none of the docs instruct people to extend the reactstrap components). This is because react itself is pretty much against inheritance (extending component) in favor of composition. https://reactjs.org/docs/composition-vs-inheritance.html
Is there something specific that you are doing that requires you to extends reactstrap component that cannot be done with composition? (can you post the full `PopoverMenuItem` class?)

**Comment by k-funk** [comment]
Thanks for the quick response!

1. I'm not so much testing the implementation of reactstrap, just the class names and props passed using enzyme's `shallow`. This has worked with reactstrap for a few years because I have the assumption that default props will change with updates, but not classnames themselves (`DropdownItem` -> `ForwardRef`). I found that mocking out reactstrap components completely would hide props that may or may not get overridden during my implementations.

A simple test:
```
    wrapper = shallow((
      <PopoverMenu>
        <PopoverMenuItem>
          ClickableThing
        </PopoverMenuItem>
      </PopoverMenu>
    ));
    wrapper.setState({ isOpen: true });
    expect(shallowToJson(wrapper)).toMatchSnapshot();
```

My component (simplified for illustration purposes):
```
import { Dropdown, DropdownItem, DropdownMenu, DropdownToggle, UncontrolledDropdown } from 'reactstrap';

export class PopoverMenuItem extends DropdownItem {}

export default class PopoverMenu extends UncontrolledDropdown {
  render() {
    const { isOpen } = this.state; // set by parent class
    const { children } = this.props;

    return (
      <Dropdown isOpen={isOpen} toggle={this.toggle}>
        <DropdownToggle tag="button" type="button" />
        <DropdownMenu right>
          {children}
        </DropdownMenu>
      </Dropdown>
    );
  }
}
```

Snapshot in `8.2.0`:
```

exports[`outputs the expected tree when ...`] = `
<Dropdown
  a11y={true}
  active={false}
  addonType={false}
  direction="down"
  inNavbar={false}
  isOpen={true}
  nav={false}
  setActiveFromChild={false}
  toggle={[Function]}
>
  <DropdownToggle
    aria-haspopup={true}
    color="secondary"
    tag="button"
    type="button"
  />
  <DropdownMenu
    flip={true}
    right={true}
    tag="div"
  >
    <PopoverMenuItem
      tag="button"
      toggle={true}
    >
      ClickableThing
    </PopoverMenuItem>
  </DropdownMenu>
</Dropdown>
`;
```

2. Understood. It was working for me as a means to write a component that has the same state and instance methods as a `UncontrolledDropdown` but is just rendered a little different. But I get the reasoning for not supporting it.

**Comment by ajacksified** [comment]
https://reactjs.org/docs/forwarding-refs.html#note-for-component-library-maintainers

> Note for component library maintainers
> When you start using forwardRef in a component library, you should treat it as a breaking change and release a new major version of your library. This is because your library likely has an observably different behavior (such as what refs get assigned to, and what types are exported), and this can break apps and other libraries that depend on the old behavior.

**Comment by TheSharpieOne** [comment]
> the public API did change in a breaking way

The inputs and outputs of the API are the same. It still accepts all of the same props and still outputs the same HTML to the page.
The whole reason `forwardRef` was used was to keep the usage of `ref` the same since we had to wrap it to consume context.

Here is what I can do. I can revert this change and leave DropdownContext broken and publish a new release to fix the 8.x branch (so the latest 8.x will not have a breaking change).

Trying to get other changes which change the API together before releasing a breaking change so that the version doesn't just jump 9, 10, 11, 12 quickly with no minors.

**Comment by ajacksified** [comment]
_react-dom_ generates the same output, but _this library_ does not produce the same output, which is why even shallow Jest snapshots break.

I don't want to come off as hostile - I use the library heavily and appreciate your work. I just want to point out what the React devs suggest, and if you do follow semver ([suggested by NPM](https://docs.npmjs.com/about-semantic-versioning)), this should be a major version bump.

**Comment by TheSharpieOne** [comment]
8.4.0 removes the breaking change following semver's procedure for accidentally releasing a backwards incompatible change as a minor version.
I have noted in the [github release page](https://github.com/reactstrap/reactstrap/releases) for all of the 8.3.x that people should use 8.4.0.

**Comment by k-funk** [comment]
> 8.4.0 removes the breaking change following semver's procedure for accidentally releasing a backwards incompatible change as a minor version.
> I have noted in the [github release page](https://github.com/reactstrap/reactstrap/releases) for all of the 8.3.x that people should use 8.4.0.
> You should be able to unpin your version so that you get the other bugfixes and such.

Great! Thank you for the quick turnaround time. Glad there was a fairly quick fix!
