### ISSUE TITLE
Unmounting a closing modal causes the body scrollbars to disappear

### ISSUE THREAD

**Issue by ghidosoft** [reactstrap/reactstrap#1819]
- components: `Modal`
- reactstrap version `#8.4.1`
- import method `es`
- react version `#16.12.0`
- bootstrap version `#4.4.1`

### What is happening?

I'm using a modal for a "delete" button, on button press I hide the modal, call an API, and when the API completes the `Modal` gets removed from the DOM.
In this case the `modal-open` class will not be removed from the `body` and the document vertical scrollbar doesn't reappear.

### What should be happening?

The `modal-open` class should be correctly removed.

### Steps to reproduce issue

1. Add and show a `Modal`
2. Close the `Modal`: set `isOpen={false}`
3. While the `Modal` is hiding remove it from the DOM

### Error message in console

No error message

### Code

I created a codesandbox demonstrating the issue:
https://codesandbox.io/s/serene-rubin-y7fpz

This is the relevant modal code:

```js
  closeAndUnmount() {
    this.setState({shown: false}, () => {
      this.setState({exists: false});
    });
  }
```

And in the render method:
```jsx
{this.state.exists && <Modal isOpen={this.state.shown}></Modal>
```

The main thing here is the two-step hide and unmount, if done together it works.

**Comment by kyletsang** [comment]
You can use the `onClosed` prop in modal for this.  This will guarantee that the modal will be fully closed prior to removing from the DOM.

See https://codesandbox.io/s/bold-resonance-cnhj8

**Comment by ghidosoft** [comment]
Hi @kyletsang, yes, that's certainly possible but I have to keep track of the pressed button and execute manually the linked action in the `onClosed` handler.

The workaround I'm currently using is by not closing the modal and simply removing it from the DOM when the API returns (e.g. the item has been deleted) but this requires that the component containing the `Modal` _knows_ about the fact that the modal will be removed from the DOM by some external means.

IMHO this is still a bug in the library, it should be able to handle this edge case.

**Comment by adam1658** [comment]
@kyletsang I've got a similar issue when rendering a modal in a react promise component (https://github.com/foundernest/react-promise-components).

React promise components allows you to create a function that when called will render a component and return a Promise. The component is able to resolve that promise with a value by using the extra `handleClose` prop the library passes in. Here's an example:

```js
const askUserIfTheyWantFood = createPromiseComponent(function FoodComponent({
  // specific to this component's functionality, nothing to do with react-promise-components:
  food, // string

  // provided by react-promise-components:
  handleClose, // Calling this will resolve the promise and unmount the component after a delay.
  transitionState, // 'entering' | 'entered' | 'exiting'
}) {
  const handleYes = () => handleClose(true); // close and resolve promise with true
  const handleNo = () => handleClose(false); // close and resolve promise with false

  return (
    <Modal
      isOpen={transitionState !== 'exiting'}
      onClosed={handleNo}
      toggle={handleNo}
    >
      <ModalHeader toggle={handleNo}></ModalHeader>
      <ModalBody>Do you want {food}?</ModalBody>
      <ModalFooter>
        <Button color="primary" onClick={handleYes}>
          Yes
        </Button>
        <Button color="secondary" onClick={handleNo}>
          No
        </Button>
      </ModalFooter>
    </Modal>
  );
});

askUserIfTheyWantFood({food: 'ice cream'}).then(console.log) // logs true or false.
```

I think it makes sense to do what I've done here - telling the `Modal` it should be open when the component is not yet about to unmount. But if the Modal closes slower than react-promise-components gives the component to unmount in, the Modal will be unmounted before it finishes it's close transition.

The defaults in this situation ([300ms?](https://github.com/reactstrap/reactstrap/blob/aa63f997e0b75a9b420945d0c5a9a78984da1e48/src/utils.js#L154) for the `Modal` to unmount and [195ms](https://github.com/foundernest/react-promise-components/blob/eb5b4abcf99b0df8113cfe63b0802199f5fe2ee3/src/PromiseComponentsFactory.tsx#L37) for react-promise-components) cause the issue to occur. I have worked around it by increasing the 'exiting' time for my usage react-promise-components to 310ms - which I believe I should be doing even without this 'modal-open' class issue in order to see the full animation.

**Even with a workaround, I still think this is a bug because you don't know where the `Modal` component will be rendered and the conditions in which it could unmount.** eg. What if an error is thrown during render inside a descendant of the modal and it is caught by an error boundary outside the modal?

**Comment by adam1658** [comment]
Another place where a modal may be rendered and be unmounted unexpectedly:

In an SPA when the modal is open on one page and you navigate to another page, the Modal may be unmounted without onClosed being isOpen being changed to false.

It seems unlikely that you would be navigating while a modal is open (because the modal is covering the rest of the page so you can't interact with links on the underlying page), but the user may navigate with the browser's back and forward buttons.

**Comment by kyletsang** [comment]
@adam1658, this is fixed in 8.5.1.  The original sandbox above no longer exhibits bug after upgrading.

**Comment by adam1658** [comment]
Thanks @kyletsang, I'll remember to check release notes first next time!

**Comment by kyletsang** [comment]
@TheSharpieOne, this issue can be closed.  Thanks!
