### ISSUE TITLE
Upgrade from ^6.5.0 to latest

### ISSUE THREAD

**Issue by bipinstha7** [reactstrap/reactstrap#1966]
Hello,
This is not an issue, its just a general question. We are using reactstrap version **6.5.0** in our project. The older reactstrap version is missing many new features. So we want to upgrade/update to the latest version i.e **8.5.1**.
My question is if we update to the latest version, does it brakes our project? Is it safe to update?
Thanks :)

**Comment by TheSharpieOne** [comment]
Note, some of the breaking changes will probably not affect you. They are "corrections" to line up with bootstrap and are mostly internal, but are technically breaking if you needed it to specifically work a certain way. If you use snapshots, you will most likely need to update them since (as noted below) some of the output tags/attributes have changed.
Each breaking change has information for mitigating it (make it work like it did before the change) if possible.

Here are the breaking changes:

### 6.x to 7.x:

- **Input**: previously `plaintext` on Input would output a 'p' tag. To better line up with bootstrap it will now output an 'input' tag. If you need a 'p' tag, provide `tag="p"` prop
- **Popover**: `Popover` will no longer dismiss when clicking away from it. To get this behaviour please use `trigger="focus"`. In 7.1.0, `trigger="legacy"` has been added to get the exact previous behavior.

### 7.x to 8.x:

- **Modal, Dropdown{*}, PopperContent, Tabs**: using new Context API, react-popper v. '1.3.3'. You MUST update your version of react to include Content API (if it is not already updated).
- **pagination-links**: Now the `next` and `previous` props are displaying single carets/chevron instead of double caret/chevron. To get the old style, use `first` and `last` props instead of `previous` and `next` respectfully and set `aria-label` to Next or Previous.
- **Popover**: `Popover` and `Tooltip` will now fade in and out (like bootstrap's default). To get the previous behavior use `fade={false}`

**Comment by bipinstha7** [comment]
Thank you @TheSharpieOne
