### ISSUE TITLE
className propTypes are a mix of 'any' and 'node'.

### ISSUE THREAD

**Issue by threehams** [reactstrap/reactstrap#209]
While working on some TypeScript type definitions, I noticed the propTypes for className throughout the project are a mix of PropTypes.any and PropTypes.node.

Is there a reason to diverge from React's default `string` type for this? If not, I can change them to be consistent throughout the project - it'll definitely simplify the typing work.

- version `3.7.0`
- components: all

**Comment by eddywashere** [comment]
I initially went with `any` to be less strict about what was sent to className prop because I imagined a consumer could make use of the `classnames` module within reactstrap components. This was early on, I don't think anyone uses className prop like this and should not be recommended. I would happily accept a pr that switches className props to be `string`. 👍

Thanks!
