### ISSUE TITLE
Dropdown problem in navbar

### ISSUE THREAD

**Issue by rvboris** [reactstrap/reactstrap#213]
Hello, i am trying to insert dropdown menu in navbar with primary color, problem is what dropdown item showing as button.

- version `3.7.1`
- components: `Navbar`

### Steps to reproduce issue

- Create navbar with primary color
- Insert dropdown nav item

[Example](http://codepen.io/rvboris/pen/QKXpVK)

**Comment by eddywashere** [comment]
@rvboris if you add color="primary" to the DropdownToggle, it should add the right class to that button. Also, if you don't want the button you can pass an "a" tag like this, http://codepen.io/eddywashere/pen/KgjQay

**Comment by rvboris** [comment]
Thank you!

**Comment by eddywashere** [comment]
@rvboris I don't think the info I provided was correct. It probably added the right class visually but I misunderstood the markup for dropdowns in the navbar. I've updated the [codepen](http://codepen.io/eddywashere/pen/KgjQay) to only use the `nav` prop in `DropdownToggle` which should provide the right markup for dropdowns in navs. This was fixed in `3.9.0`.
