### ISSUE TITLE
React class constructor pattern blocks context

### ISSUE THREAD

**Issue by jakemhiller** [reactstrap/reactstrap#27]
The constructor pattern used in most of these components:

```js
constructor(props) {
  super(props)
}
```

Ignores the other arguments passed to the component: `(props, context, updater)`

This means, if you use something that requires `context`, like react-router, it won't be passed through to the child components.

This pattern would solve that and be a little more future-proof.

```js
constructor(...args) {
   super(...args);
}
```

Though in cases where you're not doing anything else in the constructor, it's probably best just to avoid overriding it.

**Comment by jakemhiller** [comment]
example: https://github.com/reactstrap/reactstrap/blob/master/src/Container.jsx#L11

**Comment by eddywashere** [comment]
Thanks @jakemhiller. I'll look at applying that pattern to existing components and removing it where not used.

**Comment by eddywashere** [comment]
I don't believe the ability to use context is blocked when using this library in a project. Your components can use reactstrap components but must require the context types. If the library components themselves were using context, this would definitely be true.

Do you have any information about `updater` and what happens when it's not passed to to super in the constructor? I have not come across anything besides `super(props, context)` in the react docs.

**Comment by jakemhiller** [comment]
@eddywashere you're right! i just looked at the test i wrote to confirm this before posting, and there was a different issue that was preventing the context from being passed down. Seems like a good habit, but it's definitely not harmful in the way I thought it was.

`updater` looks like it is just a reference to the various state/prop update queueing functions in React:

![screenshot 2016-04-08 12 48 48](https://cloud.githubusercontent.com/assets/238023/14391145/539c125e-fd88-11e5-8f4e-e92ca870c9f9.png)

I haven't looked into how it is used.
