### ISSUE TITLE
Add props for custom widths

### ISSUE THREAD

**Issue by will-stone** [reactstrap/reactstrap#297]
I use the _custom.scss file to add additional widths, e.g. xxl. It would be nice if all the components supported this, e.g. `<Col xxl="4"></Col>`

This will mean supporting dynamic props names. Not sure how this is achieved or even if it's possible. I'll do some research.

**Comment by TheSharpieOne** [comment]
dynamic props names are possible, for sure, but the problem becomes "how does reactstrap know your extra prop is a column and not something else".
I do like the ability to define your own additional breakpoints, perhaps a more defined prop may be needed in order to inform the `Col` component that it needs to enrich and extend the class names.
Something like `<Col cols={{xxl: 4}}>` which would also allow offset/push/pull and such as `<Col cols={{xxl: {size: 4, offset: 2}}}>`. The component would be able to use the keys to determine the column name to thus be able to generate the classes accordingly.

Alternatively, something more simple could be done which would allow you use to the xxl prop are you indicated, but you would need to "configure" reactstrap to know about it. This is less effort than the first way, but I dislike the "configure before you use" type of system, as things should work out of the box. Anyways, reactstrap could expose [the array of column sizes](https://github.com/reactstrap/reactstrap/blob/master/src/Col.js#L6) or a method for manipulating it. Then you could add your custom column (such as 'xxl) and the rest of the code will now know about it and be able to pick it out of the props directly.

@eddywashere thoughts?

**Comment by eddywashere** [comment]
An options prop like `widths` could accept an array of widths, `widths=['xs', 'sm', 'md', 'lg', 'xl', 'xxl']`. The Col component is setup to process an array like that currently, and would need minor adjustment to make the first item in the array the base size. This could be something for other width dependent components as well. 

From there, you could wrap this component:

```
const CustomCol = (props) => <Col widths=['xs', 'sm', 'md', 'lg', 'xl', 'xxl'] {...props} />;
```
