### ISSUE TITLE
Navbartoggler image

### ISSUE THREAD

**Issue by camel113** [reactstrap/reactstrap#299]
I am looking for a light solution to change Navbartoggler image because I need to change the color of this. Any suggestions?

**Comment by TheSharpieOne** [comment]
This question is probably best for bootstrap itself as it pertains more to the ability to customize the styles themselves. This project only makes it easy to apply classes and added react based functionality rather than jquery (which bootstrap's js uses).

But...
Unless you want to compile bootstrap's scss in your project to override variables (which isn't that hard and is what I do since I often need very custom styles/color), you're best bet is to simply add a `className` with a custom class which overrides bootstrap's default styles.
This is because, as mentioned above, bootstrap doesn't allow this to be customized with a class or convention. The [value is in their variables](https://github.com/twbs/bootstrap/blob/v4.0.0-alpha.6/scss/_variables.scss#L619), changing/overriding it there and recompiling the css will change it for you. Or you can create your own class, copy their svg and change the color; using `className` to add your custom style to the element.

**Comment by camel113** [comment]
Thanks for your advices @TheSharpieOne ! You are right, it is not the best place to ask this question. Sorry about that.
