### ISSUE TITLE
FR: Checkbox and radio buttons

### ISSUE THREAD

**Issue by achtan** [reactstrap/reactstrap#300]
can you pls implement: 
https://v4-alpha.getbootstrap.com/components/buttons/#checkbox-and-radio-buttons

**Comment by TheSharpieOne** [comment]
dup: #273
As mentioned there, this feature already exists. Because these components are stateful, it is considered outside the scope of this project.
Some documentation is needed to show how the existing components can be used to create what you are wanting to do.

To be clear, all you need to do is use [`<ButtonGroup>`s](https://reactstrap.github.io/components/button-group/) with `<Button>`s and set the `active` props on the button which is selected. That last part is the key to it, but it is where state comes into play and this is not included.
Here is a basic demo of that using the current version of the project: http://www.webpackbin.com/EJKGaQo8z

**Comment by aminnaggar** [comment]
ps. your webpackbin is no longer there

**Comment by TheSharpieOne** [comment]
@aminnaggar webpackbin did an update, here is a new example: https://www.webpackbin.com/bins/-Km7h6x6NXUDb0_KQtmL
Note it is just an example, you shouldn't use inline functions in prod for performance reasons.
