### ISSUE TITLE
tootips not working for me

### ISSUE THREAD

**Issue by pgoldweic** [reactstrap/reactstrap#305]
### Issue description
I am unable to get the Tooltip component to work according to the instructions. Am I missing some required initialization? 
- version `#4.0.1'
- components: `Tooltip`

### Steps to reproduce issue
Here is part of a render() method for one of my components: 

    <Form inline>
    	<FormGroup color="success" >
    		<Input size="sm" type="text" value="sth"  id="someid" />
    		<Tooltip placement="right" target="someid" >Valid grades are  blah, blah</Tooltip>	
    	</FormGroup>
    </Form>

While the above does not produce any errors, the tooltip is not functional. Is there some required initialization? I am using create-react-app and npm. I have included the bootstrap css import in my index.js file (other reactstrap components seem to be functional).

**Comment by TheSharpieOne** [comment]
reactstrap does not manage the state of the tooltip (such as open/close show/hide). It does preform the actions, but you need to tell it when to show/hide via the `isOpen` prop. There is a `toggle` prop which lets you know when to change your state.

See https://reactstrap.github.io/components/tooltips/ for more information, specifically the part of the examples which deal with `toggle` and `isOpen`

**Comment by pgoldweic** [comment]
Oh, I see. However, I am interested in simply getting a tooltip displayed on rollover for an html element of some sort. Is there support for this basic usage in a simple way? (otherwise, it seems to me that I'd need to create a component for everything on the page which I expect to have rollover on, and manage state for it, which certainly doesn't seem practical).

**Comment by TheSharpieOne** [comment]
You can easily create your own reusable component based on the foundation reactstrap has laid out.
This component here essentially wraps `Tooltip` to give it state-fullness for the "basic" usage you are looking for. You would import this component instead of the `Tooltip` directly.

```javascript
import React, { Component } from 'react';
import { Tooltip } from 'reactstrap';

class SimpleTooltip extends Component {
  state = {isOpen: false};

  toggle = () => {
    this.setState({isOpen: !this.state.isOpen});
  };

  render () {
    return <Tooltip isOpen={this.state.isOpen} toggle={this.toggle} {...this.props} />;
  }
}

export default SimpleTooltip;
```
After importing your `SimpleTooltip` you could use it like so (which is your example, just using `SimpleTooltip` instead of the default `Tooltip`):
```javascript
//...
<FormGroup color="success" >
  <Input size="sm" type="text" value="sth"  id="someid" />
  <SimpleTooltip placement="right" target="someid" >Valid grades are  blah, blah</SimpleTooltip>	
</FormGroup>
//...
```
Demo: http://www.webpackbin.com/417Of-zwz

**Comment by eddywashere** [comment]
+1. The core reactstrap concepts of controlling state via props like isOpen and toggle enable what you want. Closing this out as it seems like the `isOpen` and `toggle` props aren't being provided. This library avoids uncontrolled components (it's easier to maintain and document a single way of working with components).

**Comment by allenross356** [comment]
tried to get the tooltip working for a while..

the reactstrap document for tooltip is poor quality..

so, i read this entire post.. clicked the "demo" url.. but it isn't active anymore..

i copied and pasted the code provided for the demo.. but it didn't work..

gave up after a while.. because a small tooltip isn't worth as much time..

i recommend reactstrap creators to improve the tooltip documentation to be more on-point..

thanks.
