### ISSUE TITLE
text size too big in Firefox

### ISSUE THREAD

**Issue by pgoldweic** [reactstrap/reactstrap#322]
I've noticed that my app displays on Firefox with abnormal size for the text. A ctrl- does make it better but still much bigger than on Chrome. Independently, I should not have to depend on individual users adjusting their browser settings when using the app. I noticed that Bootstrap 3 sizes seem to display with normal sizes though, so I'm wondering whether there's anything in Bootstrap 4 (or reactstrap) causing this. 
- version 4.0.1`
- os: Windows 10

Notes: I am not explicitly setting font sizes anywhere. Thanks.

**Comment by TheSharpieOne** [comment]
This issue is probably best opened with bootstrap directly. This library does not include bootstrap itself, which would be the thing affecting the font-size.
I do know that bootstrap font sizing is completely relative to the browser's font-size. See: https://github.com/twbs/bootstrap/pull/21524
I would confirm that the default font-size for your browser is 16px. Also, you can see the size which was computed using Firefox's Developer Tools, see https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Examine_and_edit_CSS#Examine_computed_CSS

**Comment by pgoldweic** [comment]
I see, thanks.  Will likely open the issue with bootstrap directly then.
