### ISSUE TITLE
DropdownItem does not accept href prop

### ISSUE THREAD

**Issue by marcdel** [reactstrap/reactstrap#367]
### What is the correct way to create a link in a NavDropdown?

- version `4.3.0`
- components: `NavDropdown`, `DropdownItem`

Is there a better way to create dropdown menu items in a navigation than doing `onClick={() => window.location.href = "/somewhere"}`?

It seems like in the context of a nav you would want the items to render as an `<a></a>` rather than a `<button></button>`. Maybe a `NavDropdownItem`?

### Steps to reproduce issue

https://codepen.io/marcdel/pen/aJYwQR

**Comment by TheSharpieOne** [comment]
You can use the `tag` prop to set it to an anchor tag but using `tag="a"`

Maybe the default tag should be `Button` instead of `button` (which will trigger [`Button`'s `href`-`anchor` tag logic](https://github.com/reactstrap/reactstrap/blob/master/src/Button.js#L66-L68)) or we can copy that logic over since there is already some [logic around the tag type](https://github.com/reactstrap/reactstrap/blob/master/src/DropdownItem.js#L73-L79).

**Comment by marcdel** [comment]
Thanks, I saw the tag attribute but didn't make the connection. That'll work fine for me for the time being 🙂

I've just started working with reactstrap, so I don't feel familiar enough to say which is the better option there.

**Comment by corydeppen** [comment]
Should `href` also be added to `propTypes` on `DropdownItem`?

**Comment by TheSharpieOne** [comment]
Yeah, that's my bad for not adding it when making the change.
