### ISSUE TITLE
<Button> type attribute should default to 'submit', not 'button'

### ISSUE THREAD

**Issue by mikeatlas** [reactstrap/reactstrap#382]
Per this recent commit last night https://github.com/reactstrap/reactstrap/commit/ebbeba75f6a05881ba6f5b34bca15c88f71eddf4 by  @TheSharpieOne ...

This caused a regression preventing us from logging into our own application. We were using a single `<Button>` element within a form for a login page, and the default behavior for a button in a form is `submit`. 

Once this change went in, our form stopped ... submitting! Changing our button to `type='submit'` does indeed fix things, but this is different from the [HTML5 button spec](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button):

> **type**
> The type of the button. Possible values are:
> **submit**: The button submits the form data to the server. This is the default if the attribute is not specified, or if the attribute is dynamically changed to an empty or invalid value.

I realize `Button` in reactstrap vs `button` in HTML5 are not the same, but it would be advisable to align with the HTM5 spec in this case.

h/t @j-francisco (thanks!)

**Comment by TheSharpieOne** [comment]
[Actual spec](https://www.w3.org/TR/html5/forms.html#attr-button-type) which does explicitly say the default is submit.... but the default type for Internet Explorer is "button" (of course)

My only argument against having submit be the default is that is not the most common use-case for the Button in this library. With bootstrap and javascript/react, most people are using them outside of forms and when they are within a form #366 happens where the intent was not to trigger submission.

This was original brought up in slack: https://reactstrap.slack.com/archives/C1WQP1G2C/p1487185000000442
> ![image](https://cloud.githubusercontent.com/assets/664714/24569451/281bf1b0-1634-11e7-993d-6ea8b9428511.png)

The best advice is to always explicitly specify the type attribute for the button, because again, IE it does not default to submit.

Perhaps some middle ground would be only defaulting to button if there is an `onClick`, which indicates that the intent is for the event to be handled by react

> button: The button has no default behavior. It can have client-side scripts associated with the element's events, which are triggered when the events occur.

**Comment by mikeatlas** [comment]
Hm, since you have ability to detect if a reactstrap `Button` is missing a `type` attribute, can you emit a console warning? That might be a suitable compromise.

**Comment by TheSharpieOne** [comment]
@mikeatlas I don't think warning will help anyone, people just expect things to work out of the box. I put up a PR which I believe is the happen medium. For your use-case, the button will not set a `type` and thus default to the browser's default (which is mostly `submit`). Only when `onClick` is set (indicating the user does not want the browser default, but their own code to run) the type is set to button, but can be overrode by the user's code.
e.g.
`<Button>Go!</Button>` -> `<button class="btn btn-secondary">Go!</button>`
`<Button onClick={this.myHandler}>Go!</Button>` -> `<button type="button" class="btn btn-secondary">Go!</button>`

**Comment by mikeatlas** [comment]
Works for me. I appreciate the solution. Thanks!

**Comment by aseroj** [comment]
@TheSharpieOne 
What if you need to pass a parameter with the click ?
Let's say : 
`<Button size="sm" color="warning" onClick={this.cancelUpload(img)} />`

**Comment by TheSharpieOne** [comment]
As with all react, you would probably want to bind the function with that parameter or abstract it to its own component.
With what you have there, that function will execute every render, passing img as it executes, returning the result of that execution to the onClick prop (probably not what you want)

**Comment by aseroj** [comment]
@TheSharpieOne 
very true, my bad.

thanks for quick response tho

**Comment by tim-montague** [comment]
A `<Button>` inside a `<Form>` should definitely NOT "default" to `type="submit"`. Bootstrap specification shows that the `type="submit"` is required for `<button>` (https://getbootstrap.com/docs/4.0/components/forms/#horizontal-form).

Why would a `<button type="button">` mutate into `<button type="submit">`?
What happens when multiple buttons are in a form?
Are these all supposed to default to `type="submit"`, and then I have to over-ride them with `type="button"`?

Buttons should default to `type="button"` regardless of where they are used.
Nothing special about an ordinary button in a form, that's why we have a submit button in the first place.

**Comment by TheSharpieOne** [comment]
@tim-montague you'd have to bring that up in https://github.com/whatwg/html as it is the html spec and not something implemented by reactstrap. If you do not explicitly specify the type on a button, that is just how it works (html has to default to something.) Reactstrap tries to help by setting the type to button when onClick is provided, but you can override it be specifying it yourself.
Bootstrap does NOT require it, they just are explicit in their examples. I suggest you also be explicit in your code as well.
