### ISSUE TITLE
What is the breaking change between v3.9.5 and v4

### ISSUE THREAD

**Issue by hsingh23** [reactstrap/reactstrap#437]
What is the breaking change between v3.9.5 and v4?
What is the migration guideline?

**Comment by eddywashere** [comment]
There's no migration guide. I'd happily accept a pr for one. Otherwise you'll need to look at the changelog. Please read all the 4.0.0 alpha release notes and the 4.0.0 release notes. Each one should have a note about breaking changes.

https://github.com/reactstrap/reactstrap/blob/master/CHANGELOG.md

**Comment by eddywashere** [comment]
Most of this was from upstream bootstrap changes between their alpha 5 -> alpha 6 release.
