### ISSUE TITLE
Modal doesn't pass `style` property to div

### ISSUE THREAD

**Issue by springuper** [reactstrap/reactstrap#443]
### Issue description

- version `#4.6.2`
- components: `Modal`

### Steps to reproduce issue

```jsx
<Modal isOpen={isOpen} toggle={this.onToggle} style={{ maxWidth: '95%' }}>
```
the `style` property doesn't apply on the final rendered `div` element. I checked the source code, and found that the problem does exist.

is it intended?

**Comment by TheSharpieOne** [comment]
Due to the complexity of the render component, it doesn't look like any extra props are passed through to any of the markup. Which element would you expect to get the styles? 
A similar issue with className caused the creation of props such as
className: PropTypes.string, wrapClassName: PropTypes.string, modalClassName: PropTypes.string, backdropClassName: PropTypes.string, contentClassName: PropTypes.string,

**Comment by springuper** [comment]
I expect [the div with 'modal-dialog' class](https://github.com/reactstrap/reactstrap/blob/master/src/Modal.js#L186) to get the styles. sometimes, it is really a convenience to use an inline style other than class name.

**Comment by TheSharpieOne** [comment]
Looks like #339 removed that.
