### ISSUE TITLE
Tab nav link should have style of 'cursor: pointer'

### ISSUE THREAD

**Issue by zhaoyao91** [reactstrap/reactstrap#450]
### Issue description
see https://reactstrap.github.io/components/tabs/
when I hover on the tab nav link, the cursor should be pointer.

- version `^4.6.2`
- components: `Nav NavItem NavLink`

**Comment by TheSharpieOne** [comment]
All styles come from bootstrap itself. They removed the pointer on everything that isnt a navigable link.

**Comment by NathanCH** [comment]
Temporary workaround is to add an href="#" to <NavLink />. 

In Bootstrap 4's implementation of tabs this makes sense since the href is used as a hook to select the tab id. But since reactstrap uses state to toggle tabs, this is a hacky workaround - the href is not used for anything except to change cursor type.

**Comment by TheSharpieOne** [comment]
I am closing this issue as it seems to be resolved or at least a bootstrap style discussion and is no longer active.

**Comment by kmiklas** [comment]
@NathanCH React starts complaining when you have a link to "#".

Adding this style works for me:

```
.nav-link {
  cursor: pointer
}
```
