### ISSUE TITLE
Col component generating incorrect html

### ISSUE THREAD

**Issue by Deppy-xx** [reactstrap/reactstrap#454]
### Issue description

The Col component is generating incorrect html, which seems to at least partly be because of incorrectly identifying the isXs flag which it seems to automatically set for the first item.

- components: `Col`

### Steps to reproduce issue

Create a component using this code:

`<Col widths={["md", "sm"]} md="4" sm="12">...</Col>`

It should generate: 
`<div class="col-md-4 col-sm-12">...</div>`

But instead it generates:
`<div class="col-4 col-sm-12">...</div>`

**Comment by TheSharpieOne** [comment]
If you are using standard bootstrap columns widths names you don't need to supply the widths prop. The widths prop is for custom widths, it is an array from smallest to largest width since the smallest width has special treatment in bootstrap which is what you are seeing. The component is working correctly.

**Comment by Deppy-xx** [comment]
OK, thanks for clarifying this.
