### ISSUE TITLE
Modal fade-out animation issue

### ISSUE THREAD

**Issue by foodgy** [reactstrap/reactstrap#473]
Hi,

I'm playing with React-Redux-Reactstrap combo. It feels fine. But I've noticed that Reactstrap modal fade-out animation brokes if **isOpen** and **toggle** props are not passed directly to Modal presentation component.

Check it out https://github.com/foodgy/react-redux-demo

Any ideas why so?

**Comment by TheSharpieOne** [comment]
The issue is not with reactstrap, but with your code and how you remove the modal. You are not toggling the modal closed, you are unmounting it. This basically means you never close the modal (and thus fade-out animation never triggers) and you rip it out of the DOM.
This happens here: https://github.com/foodgy/react-redux-demo/blob/master/src/containers/ModalRoot.js#L12

You need to toggle the modal (to `isOpen={false}`), and wait for the animations to finish before excluding it from your render.

**Comment by foodgy** [comment]
@TheSharpieOne Thank you!
