### ISSUE TITLE
'Error' message: ''errors' is missing in props validation (react/prop-types)

### ISSUE THREAD

**Issue by oopeiw** [reactstrap/reactstrap#509]
Hello I new with reactstrap and I am getting stuck at this ,Help me please

error  'className' is missing in props validation  react/prop-types

- version `#4.8.0`
- components: `model`

class MenuTopWeb extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      notificationDropdown: false,
      subMenuDropdown: false,
      modal: false
    };

    this.togglePopup = this.togglePopup.bind(this);
  }

  toggleNotification(event) {
    event.preventDefault();
    this.setState({
      notificationDropdown: !this.state.notificationDropdown,
      subMenuDropdown: false
    });
  }

  toggleSubmenu(event) {
    event.preventDefault();
    this.setState({
      subMenuDropdown: !this.state.subMenuDropdown,
      notificationDropdown: false
    });
  }

  togglePopup() {
    this.setState({
      modal: !this.state.modal
    });
  }

  render() {
    return (
      <div className={styles.menutop + ' col-lg-3 mt-lg-2'}>
  
              <Modal isOpen={this.state.modal} toggle={this.togglePopup} className={this.props.className}>
                <ModalHeader toggle={this.togglePopup}> Sign in </ModalHeader>
                <ModalBody>
                  Form Sign in here....
                </ModalBody>
                  <ModalFooter>
                    <Button color="primary" onClick={this.togglePopup}>Do Something</Button>{' '}
                    <Button color="secondary" onClick={this.togglePopup}>Cancel</Button>
                  </ModalFooter>
              </Modal>

      </div>
    );
  }
}

Thank you

**Comment by TheSharpieOne** [comment]
**This question would be best for stackoverflow. It has nothing to do with reactstrap**

The problem is within the props defined in your use of `Modal`
```
<Modal isOpen={this.state.modal} toggle={this.togglePopup} className={this.props.className}>
```
The className uses `this.props.className` but you are not defining the prop className in your propTypes.
To fix this add the follow at the end of your code (This assumes you are importing PropTypes from 'prop-types' OR PropTypes from 'react' (the latter is the older way of doing it)):
```
MenuTopWeb.propTypes = {
  className: PropTypes.string
};
```
For more information, see the package mentioned in the error message: [prop-types](https://github.com/facebook/prop-types)
Also see [Typechecking With PropTypes](https://facebook.github.io/react/docs/typechecking-with-proptypes.html) from the reactjs docs.

**Comment by oopeiw** [comment]
@TheSharpieOne Thank you Its work. :)
