### ISSUE TITLE
multi-selection-dropdown functionality not found in reactstrap

### ISSUE THREAD

**Issue by error-yatish** [reactstrap/reactstrap#519]
can't find 

> multi-selection-dropdown

 in **reactstrap**

**Comment by TheSharpieOne** [comment]
Not too sure what you mean, can you provide a link to the component within the bootstrap v4 documentation? 
You can use an `Input` with a `type` prop of select add the `multiple` prop to make it a multi-select. 
As for dropdown, you can use the existing components in a way to achieve this. Since reactstrap is just bootstrap v4 components (as stateless as possible), there isn't an out of the box single component way. Here is a demo https://www.webpackbin.com/bins/-Kput64BMivF-SpzMkIc
If you are taking about something like select2, bootstrap itself doesn't have anything like that and thus neither does reactstrap. I would suggest using react-select.

**Comment by error-yatish** [comment]
thank you @TheSharpieOne you suggest me perfectly what i need
