### ISSUE TITLE
Color prop of Badge component should be required

### ISSUE THREAD

**Issue by mtakac** [reactstrap/reactstrap#539]
### Issue description
The `Badge` component can be rendered as default without specifying any `color`. IMO `color` should be required. There isn't any default `Badge` in current version of Bootstrap and even in Reactstrap, the badge without color will not be visible. I fixed the docs in [this PR](https://github.com/reactstrap/reactstrap/pull/538), but I think we should still make the `color` required.

- Reactstrap version `#4.8.0`
- Bootstrap version `#4.0.0-beta`
- components: `Badge`

### Steps to reproduce issue
1. Render `Badge` without specifying `color` property:
```
<Badge>New</Badge>
```

Discussion about similar issue concerning `Button`: https://github.com/reactstrap/reactstrap/issues/535. Currently rendering `Button` without `color` prop will render secondary button. IMO this is inconsistent with Bootstrap but we should at least ensure that all components act in similar and predictable manner. Therefore if this is the behaviour we are after, `Badge` should work similarly as well and render secondary `Badge` if `color` is not specified.

**Comment by TheSharpieOne** [comment]
Just a note here:
For now I am leaving it as it is (only changing `default` to `secondary`). This is the path of least resistance and does not produce a breaking change. I defer the decision to make it required to @eddywashere since he originally defaulted the color even though bootstrap doesn't (since you have to manually apply the class in bootstrap) (also because I feel we should default it 😅 ).
