### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by mtakac** [reactstrap/reactstrap#540]
I find the versioning of Reactstrap a bit confusing. Wouldn't it be best to just follow the Bootstrap versioning and therefore be sure which version of Reactstrap works with which version of Bootstrap?

**Comment by TheSharpieOne** [comment]
reactstrap uses semantic versioning, which dictates when which level version changes should happen. If we followed bootstrap, we would only be able to make new versions whenever they make new versions but we cannot be locked to that as we need to make changes when react need us to make changes. Also we probably need breaking changes to better course correct when things change in the direction of reactstrap specific features (such as animation callback props and handling). 
This problem only really arises when bootstrap makes breaking changes, since the goal is to support bootstrap 4, once it is officially released per semver, bootstrap cannot make any more breaking changes.

**Comment by mtakac** [comment]
@TheSharpieOne thanks for your quick reply. Makes perfect sense. I am closing the issue.
