### ISSUE TITLE
Server side rendering and React 16

### ISSUE THREAD

**Issue by ablbol** [reactstrap/reactstrap#554]
Hi everyone.
I don't have an issue but rather couple questions:

1) Does this library work with server side rendering?
2) Does it work with React v.16?
Thanks

**Comment by virgofx** [comment]
1. Yes works with server side rendering
2. Yes works with React v16; however there are a few bugs with just a few components -  #548

**Comment by mclapa** [comment]
Hello @virgofx 
Don't mean to re open but getting an error when server side rendering

`import {NavDropdown, DropdownToggle, DropdownMenu, DropdownItem} from 'reactstrap'`

give

`ReferenceError: navigator is not defined`

Any help would be appreciated

**Comment by TheSharpieOne** [comment]
Dropdowns when open use popper.js (in the v5 alphas) which cannot be ran during server-side rendering as popper.js needs the browser's API to access more advanced features of the DOM for positioning and such. We may want to add a check to make sure the page is not being rendered on the server `isOpen` is `true`. The workaround is to not have `isOpen` be `true` when rendering server-side.
Versions before v5 used tether and I am not 100% sure what it is doing, but it probably has similar limitations.

**Comment by virgofx** [comment]
@mclapa The issue is that you're running client-side code in your constructor.  You need to move that processing into `componentDidMount` - additionally, you shouldn't render any server side display elements that are open.  

The issue you're having is really not Reactstrap specific. It's react specific. When rendering serverside you don't have access to the DOM and other top level globals (window.navigator), etc.
