### ISSUE TITLE
Tag attribute breaks <Button disabled> style

### ISSUE THREAD

**Issue by tim-montague** [reactstrap/reactstrap#562]
```
import { Button } from 'reactstrap';
import { Link } from 'react-router-dom';
```
```
<Button role="button" tag={Link} to="/endpoint" disabled>Click Me</Button>
```

This code breaks the "not-allowed" cursor that normally exists on a disabled Bootstrap button.

**Comment by TheSharpieOne** [comment]
You would need to take this issue up with bootstrap but bootstrap has done this intentionally, reactstrap doesn't do any styling.
Bootstrap PR which removed the style: https://github.com/twbs/bootstrap/pull/22403
Bootstrap issue which asked why (and has a work-around): https://github.com/twbs/bootstrap/issues/23334
Bootstrap docs, which match reactstrap's for this: https://getbootstrap.com/docs/4.0/components/buttons/#disabled-state

I'm closing this as there is nothing reactstrap can do since it is inline with what bootstrap is doing.
