### ISSUE TITLE
Tooltips on <tr> (aka: OverlayTrigger)

### ISSUE THREAD

**Issue by olmobrutall** [reactstrap/reactstrap#573]
I'm in the process of migrating a big application/framework from `react-bootstrap` to `reactstrap`. 

In React Bootstrap I have some usages of `OverlayTrigger`, a high-order component that will add a `Tooltip` / `Popup` to another component without adding any intermediate tag. 

The way `Tooltip` and `Popup` work in `reactstrap,` while simpler, requires adding a artificial container for the `Tooltip` and the `Tooltip`'s target, so you have to decide if using a `span` or `div` and, afaik, makes it hard to use it in elements like a `tr`.

Are there any benefits of the `reactstrap` approach that I'm not aware?

**Comment by TheSharpieOne** [comment]
There are no artificial containers needed, you only need an id on the target element (`<tr>` in your case) and the `<Tooltip>` component (which doesn't output anything _in-place_, it attaches the content to the body when it appears).
You can place the `<Tooltip>` anywhere in your component (such as a child of the `<tr>`). Since it doesn't output any content, react doesn't complain about something that shouldn't be in a `<tr>` being in a `<tr>`.

There are many ways to do this (placing tooltip in various locations, having the row be a seperate component, and more). I though having the row be it's own component would be more interesting, also I used `UncontrolledTooltip` instead of `Tooltip` as it is easier, letting me avoid having to create the toggle function and set state for isOpen. All of that could have been done within MyRow though.

Contrived Example: https://www.webpackbin.com/bins/-Ku-gC7YDHmUpMr4VZwP

Preview: (the gif has some color issues, view the live demo with the link above)
![tr-tooltip](https://user-images.githubusercontent.com/664714/30436300-cfc52b2e-9939-11e7-9a6d-6259e998ea12.gif)

Code: 
Main:
```jsx
import React from 'react';
import { Container, Table, UncontrolledTooltip } from 'reactstrap';
import MyRow from './MyRow';

class ReactstrapExample extends React.Component {
  render() {
    return (
      <Container className="py-4">
        <Table striped>
          <tbody>
            <MyRow>
              <td>No tooltip</td>
              <td>No tooltip</td>
              <td>No tooltip</td>
            </MyRow>
            <MyRow id="myothertooltiprow" placement="bottom" tooltipContent="Hello from the other side">
              <td>tooltip below this row</td>
              <td>tooltip below this row</td>
              <td>tooltip below this row</td>
            </MyRow>
            <MyRow>
              <td>No tooltip</td>
              <td>No tooltip</td>
              <td>No tooltip</td>
            </MyRow>
            <MyRow id="mytooltiprow" tooltipContent="Hello from the other side">
              <td>tooltip above this row</td>
              <td>tooltip above this row</td>
              <td>tooltip above this row</td>
            </MyRow>
          </tbody>
        </Table>
      </Container>
    );
  }
}
export default ReactstrapExample
```

MyRow:
```jsx
import React from 'react';
import { UncontrolledTooltip } from 'reactstrap';

export default function MyRow ({ tooltipContent, placement = 'top', children, ...props }) {
  return (<tr {...props}>
      {children}
      {tooltipContent && props.id &&
        <UncontrolledTooltip placement={placement} target={props.id}>
          {tooltipContent}
        </UncontrolledTooltip>
      }
    </tr>);
}
```

**Comment by olmobrutall** [comment]
Awesome answer, thank you very much! I was aware that the tooltip could be anywhere but didn't think inside was also an option. Of couse! 

This solves all my concerns with the Tooltip itself and with the reactstrap comunity.

Thanks!

**Comment by godmar** [comment]
Is there a way to do this without an id attribute?

I'd like to place this in a component, having to create unique id for every time the component is instantiated seems a bit burdensome. Is there an alternative?

**Comment by TheSharpieOne** [comment]
For a11y you need that ID for anything with a tooltip, also if you are mapping over a set of data, you already need a unique key for react. If you are not mapping data then you can just make the IDs up in the code.
