### ISSUE TITLE
Prevent Reactstrap Dropdown clashing with Bootstrap's JQuery

### ISSUE THREAD

**Issue by wasabigeek** [reactstrap/reactstrap#579]
### Issue description
I'm in the process of migrating from Bootstrap/JQuery to Reactstrap, and wondered if there was a way for Reactstrap and Bootstrap **Dropdowns** to co-exist while changing individual components. Right now the toggling is messed up, needing a few clicks to open/close the DropdownMenu. When I remove the Bootstrap/JQuery it works fine, so I suspect the `data-toggle` attribute is causing the issue, as the Bootstrap [code](https://getbootstrap.com/docs/4.0/components/dropdowns/#via-data-attributes) will look for this attribute.

- version `#4.8.0`
- components: `Dropdown`

### Steps to reproduce issue

- Create a Reactstrap Dropdown
- Add JQuery and bootstrap.min.js

https://codepen.io/wasabigeek/pen/rGeJEL

**Comment by TheSharpieOne** [comment]
I'm not seeing the issue with the codepen you created. Part of it may be because bootstrap v4 alpha 6 requires Tether which was no included in your codepen. I add it and still did not see what you describe.
But really, I am not sure why reactstrap is _really_ adding `data-toggle`. Yes, reactstrap tries to output the same classes and structure as bootstrap, but in this case it is not really needed since bootstrap is using `data-toggle` to attach events to the element and not for a11y or anything like that. reactstrap just doesn't need it so it should probably be removed.
For now, a temporary workaround would be to provide your own `data-toggle` prop and set it to something else (like an empty string). This way it to no longer be `data-toggle="dropdown"`, it will be something like `data-toggle=""` which should not trigger bootstrap's JS.

**Comment by wasabigeek** [comment]
@TheSharpieOne thanks for the response!

For the Codepen, what I get is:

- Click once, Dropdown menu opens, click again, it closes - works fine
- Click again, twice - _nothing happens except the button changes focus a little_
- Click again, Dropdown menu opens, repeat

Tried using v5 (using this [fork](https://github.com/reactstrap/reactstrap/pull/574#issuecomment-330721679)), but still get the same issue, I think it's because `data-toggle="dropdown"` is still in the [DropdownToggle.js](https://github.com/reactstrap/reactstrap/blob/v5/src/DropdownToggle.js). After removing [L49](https://github.com/SimeonC/reactstrap/blob/v5/lib/DropdownToggle.js#L49) and [L57](https://github.com/SimeonC/reactstrap/blob/v5/lib/DropdownToggle.js#L57) I don't get the issue anymore 😄

**Comment by TheSharpieOne** [comment]
In v5 you can override the `data-toggle` to set it to something else and it will not affect the dropdown as it does in previous versions.
Also, here is what I see when using the codepen provided: (each click is denoted with the black circle and at the beginning I do a refresh (which you can see in gif) to ensure it is the first time being clicked)
![dropdown-click](https://user-images.githubusercontent.com/664714/30649939-99ef75c6-9def-11e7-8a5a-a1980b347dbd.gif)

**Comment by wasabigeek** [comment]
I'll try overriding data-toggle once v5 is out, that sounds good.

This is what I see (the software I used didn't record all the clicks correctly, but it should be clear enough):
![issue](https://user-images.githubusercontent.com/4256705/30732758-a041b570-9fa6-11e7-98a8-45a4bb36e671.gif)

I'm using Windows 10 + Chrome 60.0.3112.113, maybe that has something to do with it.

**Comment by supergibbs** [comment]
Sounds like this isn't an issue anymore in v5.0.0

**Comment by wasabigeek** [comment]
@supergibbs is the v5 beta available via npm now?

Thanks for all the hard work!

**Comment by supergibbs** [comment]
Yep!

`npm install reactstrap@5.0.0-beta`
