### ISSUE TITLE
How to clollapse navbar sooner the 576px?

### ISSUE THREAD

**Issue by NemethNorbert** [reactstrap/reactstrap#582]
I simply have a situation, where I need to collapse the navigation bar sooner then it actually triggers.
I tried to do it in css, hovever Bootstrap applies `display:flex!important;` before 576px to navbar-collapse, and if I force any display value to it, the module will stop working.
I am not shure it`s the right place to ask help, but I thought it worths a try.
Thank you in advance!

**Comment by TheSharpieOne** [comment]
If you are just trying to change the breakpoint from `xs` (which is the default when you use `toggleable` on `Navbar`) to something else (like `sm`) you can provide the breakpoint you want:

```jsx
<Navbar toggleable="sm">
  // ...
</Navbar>
```

If you are not trying to use a predefined breakpoint then StackOverflow might be the best place for this since this really doesn't have anything to do with reactstrap (as reactstrap doesn't have any css) and this is a CSS issue/question.
To point you in the right direction, there are several ways to solve this issue:
media queries are used to control when styles are applied at specific breakpoints. You can also override bootstrap's styles (even ones marked with `!important`) by providing a rule with a greater [specificity](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity) with `!important` as well.
You can also customize bootstrap itself by changing a SASS variable and building your own version of it to include in your project (I do this all of the time to customize colors and such without needing to override). [Here](https://github.com/twbs/bootstrap/blob/65ffb1c3b6e94440812a2e228cb8e8be512652ec/scss/_variables.scss#L205-L211) is where that value comes from, you can define it before loading the script and it will use your values.

**Comment by NemethNorbert** [comment]
Thank you! This was the solution I was hoping for, perfect. I just could not find it in the docs.
