### ISSUE TITLE
docs site is out of sync with npm version

### ISSUE THREAD

**Issue by deltaskelta** [reactstrap/reactstrap#612]
### Issue description

- version `#4.8.0`
- components: `Popover`

### Steps to reproduce issue

The `4.8.0` release uses the Popover components `<PopoverTitle>` and `<PopoverContent>` but they are not in the `4.8.0` release. This issue took me quite a while to chase down, I believe the docs site should be in sync with what a normal `npm` install will give the user...
- ...

**Comment by virgofx** [comment]
We are migrating to version 5.0.0 fairly quickly and everything was in a branch previously however now merged into master ... it shouldn't be long before 5.0.0 gets stable

**Comment by TheSharpieOne** [comment]
#195 needs to be implemented to allow people to view docs for previous versions. Right now the docs have `npm install --save reactstrap@next react react-dom` indicating they works with the `@next` version (in one place, but needs to be update in other place), but yes, you cannot see docs for the normal version now.

**Comment by albertkim** [comment]
Do you guys feel that Reactstrap next with Bootstrap beta is relatively production ready as is?

**Comment by TheSharpieOne** [comment]
Speaking strictly for reactstrap. I am using reactstrap v4.x in production now (with a [uikit based on bootstrap alpha.6](https://github.com/Availity/availity-uikit/tree/feature/v3)). v5 is just as production ready (I just cannot use it in production myself because that uikit I mentioned doesn't support the bootstrap beta yet)

As far as making the update from v4.x to v5.x and the current state of the v5 alpha, I don't foresee any more breaking changes.

There are a few known issues (when using with react 16), but none are "show stoppers" (AFAIK). At worst, some animations will not work and refs within modals do not get set in the order they should (marked as a wontfix in react) both issues only with react 16.
It's not 100% drop-in replacement (even though I tried). There are some breaking changes which will require you to make some changes when upgrading.

I deprecated as much as I could (props and components) without removing anything, but some stuff (e.g. tether props) simple do not exist anymore and do not have direct a replacement or upgrade path. (For tether props specifically, I don't believe they were used as much and many of the features enabled by them are now available via various props on components when use the `PopperContent`)
We are trying to fix the animation issues with react 16 before cutting v5 officially though.

Give it a try, start your upgrade development using the alpha and if you run into any problems, open an issue.

As I said above, I don't foresee any more breaking changes, so any work you do to upgrade will still be valid when v5 officially releases.

**Comment by m-salamon** [comment]
I switched from react-bootstrap to **reactstrap** and its been amazing so far, the reason I switched is because **reactstrap is updated with bootstrap 4** and everything works seamlessly (you can't use bootstrap 4 css styles with react-bootstrap you will get messed up big time.), 

> we should get this to become the standard in react projects and contribute to the code.

**Comment by TheSharpieOne** [comment]
With the release of 5.0.0, the docs are more in sync, but they will still be slightly ahead as they are generated from master.
