### ISSUE TITLE
UncontrolledTooltip doesn't close when element is disabled

### ISSUE THREAD

**Issue by Chimaytric** [reactstrap/reactstrap#634]
### Issue description

- components: `UncontrolledTooltip`
- reactstrap version `5.0.0-alpha.3`
- import method `es` 
- react version `15.6.1`
- bootstrap version `4.0.0-beta`

### What is happening?

The tooltip stays up when the described element (in my case is a button) goes disabled and the pointer isn't over it

### What should be happening?

Tooltip should disappear

**Comment by TheSharpieOne** [comment]
Here is a demo of the issue in reactstrap: https://www.webpackbin.com/bins/-KwLjPRC5c0Q1AFZY1dP

This is coming from the `Tooltip` itself and really just how the browser works. Disabled elements do not trigger events, so no `mouseleave` event is dispatched by the browser and thus the `toggle` callback is not called and the tooltip stays open.
This issue is not unique to reactstrap, bootstrap has the same problem: https://codepen.io/TheSharpieOne/pen/EwebRe
Since reactstrap tries to mimic bootstrap as closely as possible, I would expect it to work this way because this is how it works in bootstrap.
You can open an issue with bootstrap. If they fix it, we will fix it in reactstrap (I say this mostly because I am not sure how to fix it and would need to see how bootstrap solves the issue).

**Comment by Chimaytric** [comment]
Thanks for your answer, I'll see with Bootstrap then !

By the way, I solved the problem in my case by only rendering the tooltip if the button isn't disabled (with the flag I use to disable the button) looks like : 
```
export default Example = (props) => {
    const myTooltip = (!props.isDisabled && props.tooltipText) 
        ? <UncontrolledTooltip placement="top" target="UncontrolledTooltipExample">{props.tooltipText}</UncontrolledTooltip> 
        : null

    return (
        <Button id="UncontrolledTooltipExample">
            Click me !
            {myTooltip}
        </Button>
    )
}
```

**Comment by TheSharpieOne** [comment]
That's a good trick, thanks for sharing that so others can use it.

I'm closing this for now. If bootstrap is able to figure out a better way, we can implement it. Until then, the workaround you mentioned is the way to go.

**Comment by charlex** [comment]
Another solution that might be a bit more generic (although I'm sure more costly computationally) for folks is to use the event of a user clicking away from the target of the tooltip to force hide a controlled `<Tooltip />`.

This would at least provide a safety valve for users to fix this problem on their own with just a simple mouse click.

**Comment by charlex** [comment]
Here is the code I am planning on using. I am a bit concerned about the amount of listeners thhis will generate on pages with many tooltips, but we'll see. Maybe I should do a combo of what @Chimaytric  has done and only turn on the listeners if the element can possibly be disabled.
