### ISSUE TITLE
DropDownItem inside NavDropdown getting focus line

### ISSUE THREAD

**Issue by Liooo** [reactstrap/reactstrap#661]
### Issue description

- components: `DropDownItem`
- reactstrap version `5.0.0-alpha.3`
- bootstrap version `4.0.0-beta.2`

### What is happening?
Shows the focus line around the link on click

![tabindex](https://user-images.githubusercontent.com/1630378/32138736-0af0157c-bc73-11e7-9f5a-8af3170da973.gif)

### What should be happening?
the focus line shouldn't show.
(correct behaviour from [bootstrap doc](https://v4-alpha.getbootstrap.com/components/navbar/)
![nav-drop](https://user-images.githubusercontent.com/1630378/32138734-048d5d02-bc73-11e7-9561-f958eb87990d.gif)

### Solution
Briefly comparing the Element against the original bootstrap's one, looks like there's tabIndex set on the element [on this line](https://github.com/reactstrap/reactstrap/blob/master/src/DropdownItem.js#L95) in reactstrap side, which isn't in original BS. Removing the line fixed the issue in my environment. What's the purpose of this tabIndex?

**Comment by TheSharpieOne** [comment]
It works the same way as Bootstrap, just defaulting to better accessibility. By default, if you do not provide an `href` on the `DropdownItem` it will create a button (`button`) instead of a link. If you do provide an `href` on the `DropdownItem`, it will create an link/anchor (`a`) which is what bootstrap's docs have. 

The difference between a link and a button that a link navigates the user to a new resource, taking them away from the current context. A button toggles something in the interface, like a video player; or triggers new content in that same context.

So, if you are navigating the user, you should be using the `href` to take the user to the new page (this applies for SPAs; `Link` from react-router (and others like it) can be used as the`tag` and will output an `a` with an `href` and work as bootstrap's docs do).
If you are just trigging the content on the page to change, then button is what you should be using. reactstrap doesn't include any styles, and if you think that the item should not get the outline style, you might want to open an issue with bootstrap (stating that for accessilbility, a button should be used, but when a button is used it does not match the link styles).

If you don't care about accessibility, you can just provide `href="#"` like bootstrap's docs and reactstrap will output the an `<a>` with that `href`. You can also provide `tag="a"` to output an anchor without an `href`, but that is not recommended and bad things happen when achor tags do not have an href.

Exmaple showcaing the difference between using and not using `href` with `DropdownItem`: https://www.webpackbin.com/bins/-KxhnjuLlS0za-wW7EZ9

**Comment by Liooo** [comment]
Ohhh right didn't notice, thanks for the detailed answer :)

**Comment by TheSharpieOne** [comment]
I'm closing this since the the issue appears it was answered above. Please comment and it will be opened if you feel the issue has not been resolved / the question has not been answered
