### ISSUE TITLE
Button dropdown size

### ISSUE THREAD

**Issue by mking-clari** [reactstrap/reactstrap#69]
To make a small button group with a small dropdown, I am passing `btn-group-sm` to `ButtonDropdown`.

```
<ButtonGroup
            size="sm"
          >
            <Button color="primary">Grid</Button>
            <Button color="secondary">Chart</Button>
            <ButtonDropdown className="btn-group-sm" isOpen={this.state.open} toggle={this.toggle}>
              <DropdownToggle caret>
                <Button>Dropdown</Button>
              </DropdownToggle>
              <DropdownMenu>
                <DropdownItem>Dropdown Link</DropdownItem>
                <DropdownItem>Dropdown Link</DropdownItem>
              </DropdownMenu>
            </ButtonDropdown>
          </ButtonGroup>
```

Do you think this is the right way to do this? Should ButtonDropdown accept a size parameter?

From one point of view, I think it's best for ButtonDropdown to inherit size from its outer ButtonGroup, but at the same time I don't reactstrap to deviate too much from the core library's behavior.

**Comment by eddywashere** [comment]
Reading through docs. It looks like changing button sizes within a group should have done the trick. I guess because the dropdown is nested, it loses that styling. That's unfortunate and maybe a bootstrap 4 issue that should be fixed (within this context). I think button dropdown should accept a size since it renders a group. Good work around and thanks for reporting this.
 
- [ ] Add size property to ButtonDropdown
