### ISSUE TITLE
Nav navbar element broken

### ISSUE THREAD

**Issue by JonathanRys** [reactstrap/reactstrap#712]
https://reactstrap.github.io/

- components: Nav
- reactstrap version `4.8.0`
- import method `umd/csj/es` (if umd, are you using the "full" version (only for v5+)?)
- react version `15.6.2 or 16.1.1`
- bootstrap version `3.3.7 or 4.0.0-beta.2`

### What is happening?
Toggle is broken and some other styling issues are causing odd-looking UIs

### What should be happening?

I expect toggle to hide and show the menu options

### Steps to reproduce issue

1. Go to https://reactstrap.github.io/ or https://reactstrap.github.io/components/navbar/
2. Use menu at top of screen

### Error message in console

N/A

### Code

      <div>
        <Navbar color="faded" light expand="md">
          <NavbarBrand href="/">reactstrap</NavbarBrand>
          <NavbarToggler onClick={this.toggle} />
          <Collapse isOpen={this.state.isOpen} navbar>
            <Nav className="ml-auto" navbar>
              <NavItem>
                <NavLink href="/components/">Components</NavLink>
              </NavItem>
              <NavItem>
                <NavLink href="https://github.com/reactstrap/reactstrap">Github</NavLink>
              </NavItem>
            </Nav>
          </Collapse>
        </Navbar>
      </div>

**Comment by TheSharpieOne** [comment]
The documentation you referenced is for a newer version of reactstrap. You'll need to use the toggleable prop instead of expand
You should also use bootstrap alpha.6 with your version of reactstrap.
It is recommended to use the latest reactstrap (which can be installed using the installation instructions on the docs) with the latest version of bootstrap (beta.2)

**Comment by kat15** [comment]
@TheSharpieOne  'newest' version on npm is 4.8.0 :(
