### ISSUE TITLE
How to set size

### ISSUE THREAD

**Issue by Nahasean94** [reactstrap/reactstrap#744]
How do I write the size property in modals which I see is a PropType of String datatype. I have a thumbnail which if the user clicks on it, a modal with the whole image is displayed. Unfortunately the image is larger than the modal width and bleeds outs of the edges of the modal. How do I control the width of the modal to allow the whole image to fit?

**Comment by TheSharpieOne** [comment]
This question would probably be best for bootstrap itself as it deals with styles and extending the bootstrap framework. Reactstrap doesn't have any styles, only applying bootstrap classes.

**Comment by supergibbs** [comment]
The only two alternate sizes built in are `sm` and `lg` which correspond to [modal sizes](http://getbootstrap.com/docs/4.0/components/modal/#optional-sizes). If you add a class to your project called `modal-xl` you can then use `xl` since `reactstrap` just appends your size string to `modal-`. You should also look into [responsive images](http://getbootstrap.com/docs/4.0/content/images/#responsive-images) to contrain your image to the modal.
