### ISSUE TITLE
Is it possible to display modal content inline in html?

### ISSUE THREAD

**Issue by syabro** [reactstrap/reactstrap#756]
It's useful to test modal design and behaviour with storybooks

**Comment by TheSharpieOne** [comment]
Currently you can use the inner modal components (`ModalHeader`, `ModalBody`, and `ModalFooter`), but you cannot use `Modal` if you want it to display inline. You'll have to just wrap the inner components with `<div className="modal" tabIndex="-1" role="dialog"><div className="modal-dialog" role="document"><div className="modal-content" role="document">` manually.
Also, bootstrap doesn't support showing it inline. bootstrap's docs have a special style to set the display to `block` so you'll need that as well.

It would be fairly simple for you to add an InlineModal component to you project which will add/wrap the children with those divs. It doesn't make sense for reactstrap to add it since bootstrap doesn't support it without extra styles.

Example: https://stackblitz.com/edit/reactstrap-v5a4-inline-modal?file=InlineModal.js
