### ISSUE TITLE
CSS not loaded

### ISSUE THREAD

**Issue by jalanga** [reactstrap/reactstrap#778]
### Issue description

- components: Button
- reactstrap version `5.0.0-alpha.4`
- react version `16.2.0`
- bootstrap version `4.0.0-beta.3`

### What is happening?
I am importing the button, I am rendering it, I can see the button but the style is not applied. The css is imported I can see it, but is not applied to the button

![image](https://user-images.githubusercontent.com/8805079/34950502-030a70aa-fa1c-11e7-8e60-36b471be29a9.png)

![image](https://user-images.githubusercontent.com/8805079/34950521-10624b60-fa1c-11e7-98cd-aab00f1f1838.png)

I am using it inside electron.
My dependencies:

```
    "animated": "^0.2.0",
    "auto-launch": "^5.0.1",
    "bootstrap": "^4.0.0-beta.3",
    "classnames": "^2.2.5",
    "devtron": "^1.4.0",
    "electron-debug": "^1.2.0",
    "electron-store": "^1.2.0",
    "electron-sudo": "^4.0.12",
    "history": "^4.6.3",
    "lodash": "^4.17.4",
    "mdi": "^2.0.46",
    "prop-types": "^15.5.10",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-google-maps": "^9.4.5",
    "react-hot-loader": "3.1.3",
    "react-jss": "^7.0.2",
    "react-redux": "^5.0.6",
    "react-router": "^4.2.0",
    "react-router-dom": "^4.2.2",
    "react-router-redux": "^5.0.0-alpha.6",
    "react-transition-group": "^2.2.0",
    "reactstrap": "^5.0.0-alpha.4",
    "recompose": "^0.26.0",
    "redux": "^3.7.2",
    "redux-form": "^7.2.0",
    "redux-saga": "^0.16.0",
    "redux-thunk": "^2.2.0",
    "semantic-ui-flag": "^2.2.11",
    "source-map-support": "^0.5.0",
    "sudo-prompt": "^7.1.1",
    "warning": "^3.0.0",
    "winston": "^2.3.1"
```

Code:
```
// @flow
import React from 'react';
import { ConnectedRouter } from 'react-router-redux';
import { Container, Button } from 'reactstrap';

type RootType = {
  store: Object,
  history: Object
};


export default function Root({ store, history }: RootType) {
  return (
    <Container>
      <Button color="primary">primary</Button>

    </Container>
  );
}
```

Imported css in index.js as:
```import 'bootstrap/dist/css/bootstrap.css';```

**Comment by jalanga** [comment]
My bad, correct import is:
```import '!style-loader!css-loader!bootstrap/dist/css/bootstrap.css';```

**Comment by oleggalimov** [comment]
Thanks, that was helpful. Why 
`import` `'!style-loader!css-loader!bootstrap/dist/css/bootstrap.css';`
is work, but in the official documentation is `import 'bootstrap/dist/css/bootstrap.css'; ` which is not working?

**Comment by flavioribeiro** [comment]
pretty helpful thanks @jalanga

**Comment by youngheart12** [comment]
./src/index.js
  Line 3:  Unexpected '!' in '!style-loader!css-loader!bootstrap/dist/css/bootstrap.css'. Do not use import syntax to configure webpack loaders  import/no-webpack-loader-syntax

Search for the keywords to learn more about each error.

i am getting this error while importing .how to fix this .

**Comment by TheSharpieOne** [comment]
@youngheart12 See https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-webpack-loader-syntax.md

**Comment by donenam** [comment]
Are you using react js? 

Sent from Yahoo Mail on Android 
 
  On Fri, Feb 22, 2019 at 2:10 PM, Dilip Kumar<notifications@github.com> wrote:   
./src/index.js
Line 3: Unexpected '!' in '!style-loader!css-loader!bootstrap/dist/css/bootstrap.css'. Do not use import syntax to configure webpack loaders import/no-webpack-loader-syntax

Search for the keywords to learn more about each error.

i am getting this error while importing .how to fix this .

**Comment by donenam** [comment]
I fixed my css issues with a code..in the package json file..  Am not with my pc now.  I will forward it later if you need. 

Sent from Yahoo Mail on Android 
 
  On Sat, Feb 23, 2019 at 2:31 AM, Chinonson Enam Ibeh<enamibeh@yahoo.com> wrote:   Are you using react js? 

Sent from Yahoo Mail on Android 
 
  On Fri, Feb 22, 2019 at 2:10 PM, Dilip Kumar<notifications@github.com> wrote:   
./src/index.js
Line 3: Unexpected '!' in '!style-loader!css-loader!bootstrap/dist/css/bootstrap.css'. Do not use import syntax to configure webpack loaders import/no-webpack-loader-syntax

Search for the keywords to learn more about each error.

i am getting this error while importing .how to fix this .

**Comment by drindc24** [comment]
Having same problem as @youngheart12. Here's my webpack config file:

`const getStyleLoaders = (cssOptions, preProcessor) => {
    const loaders = [
      isEnvDevelopment && require.resolve('style-loader'),
      isEnvProduction && {
        loader: MiniCssExtractPlugin.loader,
        options: Object.assign(
          {},
          shouldUseRelativeAssetPaths ? { publicPath: '../../' } : undefined
        ),
      },
      {
        loader: require.resolve('css-loader'),
        options: cssOptions,
      },
      {
        // Options for PostCSS as we reference these options twice
        // Adds vendor prefixing based on your specified browser support in
        // package.json
        loader: require.resolve('postcss-loader'),
        options: {
          // Necessary for external CSS imports to work
          // https://github.com/facebook/create-react-app/issues/2677
          ident: 'postcss',
          plugins: () => [
            require('postcss-flexbugs-fixes'),
            require('postcss-preset-env')({
              autoprefixer: {
                flexbox: 'no-2009',
              },
              stage: 3,
            }),
          ],
          sourceMap: isEnvProduction ? shouldUseSourceMap : isEnvDevelopment,
        },
      },
    ].filter(Boolean);
    if (preProcessor) {
      loaders.push({
        loader: require.resolve(preProcessor),
        options: {
          sourceMap: isEnvProduction ? shouldUseSourceMap : isEnvDevelopment,
        },
      });
    }
    return loaders;
  };`

**Comment by drindc24** [comment]
Having same issues as @youngheart12 , am a beginner in react and the accepted answered above is using an old config file from webpack

**Comment by TheSharpieOne** [comment]
There is nothing special or reactstrap specific for importing CSS (such as bootstrap's CSS).
The easiest way is to just link to the CSS hosted on a CDN as recommended by bootstrap: https://getbootstrap.com/docs/4.3/getting-started/introduction/#css
If you want to `require`/`import` CSS, then you need to have your build tool handle `.css` (or even `.scss`/`.sass`) files, else it will not know what to do with the file and probably assume that it is javascript (and blow up since CSS is not JavaScript).
In webpack, a loader (or a few loaders) are needed. You can find out more about webpack loaders and loading CSS via webpack on webpack's documentation site: [Loaders](https://webpack.js.org/concepts/loaders/) and [css-loader](https://webpack.js.org/loaders/css-loader/)
Using something like CRA will preconfigure your webpack in a common/opinionated way. It supports loading CSS out of the box.

The issue that @youngheart12 and @drindc24 are running into is that they have a project which specific forbids using [inline loaders](https://webpack.js.org/concepts/loaders/#inline). An inline loader is a modification to the import statement to make the import be a non-standard import. It adds which loader you want to use when loading the file to the file name string.
For instance this is a legit import which many systems understand:
```js
import 'bootstrap/dist/css/bootstrap.css';
```
this is a webpack specific import which webpack understands
```js
import '!style-loader!css-loader!bootstrap/dist/css/bootstrap.css';
```
The problem with the webpack specific import is that you are coupling your imports to a specific build tool (which is considered bad practice).
Because of this, an eslint rule was created to find webpack specific import instances and throw an error. This eslint rule is in @youngheart12 and @drindc24 project, they can disable it to allow them to do the inline imports OR they can add the imports to their webpack configuration (see [css-loader](https://webpack.js.org/loaders/css-loader/)).

**Comment by youngheart12** [comment]
Thank you Evan sharp. Now I got to know where I was making a
mistake.Thankyou once again Evan.

**Comment by youngheart12** [comment]
from where i can get the options of disabling eslint rules

**Comment by mkotsollaris** [comment]
`import 'bootstrap/dist/css/bootstrap.css';` did for me.

Example:
```
import React from 'react';
import {
    Dropdown,
    DropdownToggle,
    DropdownMenu,
    DropdownItem
} from "reactstrap";
import 'bootstrap/dist/css/bootstrap.css';

export default class MyCustomDropdown extends React.Component {

    toggle = () => {
        this.setState(prevState => ({
            dropdownOpen: !prevState.dropdownOpen
        }));
    }

    render() {
        return <Dropdown isOpen={this.state.dropdownOpen} toggle={this.toggle}>
            <DropdownToggle caret>Dropdown</DropdownToggle>
            <DropdownMenu>
                <DropdownItem>Foo Action</DropdownItem>
                <DropdownItem>Bar Action</DropdownItem>
                <DropdownItem>Quo Action</DropdownItem>
            </DropdownMenu>
        </Dropdown>;
    }
}
```

**Comment by fulin426** [comment]
@mkalish For some reason when I ran a build the CSS was loss. I decided to import the bootrap css to my top level app component. Thanks this helped!
