### ISSUE TITLE
Progress

### ISSUE THREAD

**Issue by eddywashere** [reactstrap/reactstrap#78]
http://v4-alpha.getbootstrap.com/components/progress/

- [ ] Progress
  - animated
  - striped
  - color

**Comment by TheSharpieOne** [comment]
While this component is relatively simple, the problem lies with HTML5, bootstrap, and their being different way to render what is essentially the same thing.
I am all for using HTML5 components, but for better backwards compatibility at no real cost; I would use the `div` elements over `progress`. Even for modern browsers (as in, do not wrap the `div` within a `progress` element).
[Animation doesn't seem to work on most modern browsers anyways](https://github.com/twbs/bootstrap/issues/17148) (also, [this comment](https://github.com/twbs/bootstrap/issues/17148#issuecomment-133792129) from the linked issue may suggest that bootstrap will itself go back to just the `div`)

What do you think?

**Comment by eddywashere** [comment]
Nice find! I tried creating a div version without the progress element wrapping it and it didn't seem to show a progress bar at all. If it does work without progress, that sounds like a better option. Otherwise, I think sticking to the progress element is not so bad since it's broken in bootstrap and can be fixed on their end. If the markup does change the component can be updated without people having to worry too much about what's changed between bootstrap releases.

**Comment by TheSharpieOne** [comment]
I forgot I had add some custom styles to get the `div` to work in all browsers. This is because [bootstrap only targets the `div` in IE9](https://github.com/twbs/bootstrap/blob/af6eaf54387a9eb8e81bc99899a42422babb9617/scss/_progress.scss#L68) which is blah.
For now, we can just go with `progress`, using the [`div` fallback](http://v4-alpha.getbootstrap.com/components/progress/#ie9-support) within the progress so it _should_ work with IE9. We can have the animated props which will add the class, but animations will not work until bootstrap fixes them. It probably the best route.
