### ISSUE TITLE
Incomplete document for pagination

### ISSUE THREAD

**Issue by mspattar** [reactstrap/reactstrap#790]
### Issue description

- components: `https://reactstrap.github.io/components/pagination/`
- reactstrap version `^4.8.0`
- import method `umd/csj/es` (if umd, are you using the "full" version (only for v5+)?)
- react version `15.6.x`
- bootstrap version `#x.x.x`

### What is happening?

There is no proper code for creating pagination, only the HTML/JSX is there. How to create pagination by  binding to list of items. What should be there in PaginationLink href? Its not clear and not usable.
### What should be happening?
Please share sample code for for binding pagination to a list of items. A function when pagination buttons are clicked to change the table contents. 

Please  update documentation or share an example.

**Comment by TheSharpieOne** [comment]
The implementation of pagination is left up to the user. This is the same for bootstrap itself, only providing styles and no functionality. Bootstrap's docs are also the same, no binding. 
There are many ways to page through data (in memory, via ajax, or something in between) and many ways to display the data. There are also many ways the binding can work. It can trigger navigation, changing the page number in the URL (which can then trigger other things) or it could call some callback in code. Because there are many options and many opinions, all of this is intentionally left up to the user; giving the user more power. Reactstrap only provides easy to use components for applying bootstrap styles.
If you wanted, you can make a component which utilizes reactstrap for UI and provides the way you want to implement pagination. You can package that as a separate npm module and we can add it to the the readme.

**Comment by jamesmckeon** [comment]
I created a really simple pagination component using reactstrap.  Here's the [repo](https://github.com/jamesmckeon/reactstrap-pager)

**Comment by jmditsolutions** [comment]
Here's a codepen showing how I used it: https://codepen.io/joedazza/pen/BVXVej

**Comment by jammeraal** [comment]
Appreciate the examples. I know this is late, but I just started using the library.  I believe that the original title of this issue is still valid, "Incomplete Documentation."  It is also possible I missed something as a core concept :). Both @jamesmckeon and @dazzatron gave examples where PaginationLink is supplied with a prop of "onClick".  The proptypes defined for PaginationLink, [https://reactstrap.github.io/components/pagination/](url) , does not include onClick.
