### ISSUE TITLE
Importing SCSS not working in reactstrap

### ISSUE THREAD

**Issue by vinaybedre** [reactstrap/reactstrap#806]
### Issue description
Please note I am not using ReactJS, but PreactJS

- components: `all`
- reactstrap version `#5.0.0-beta`
- preact version `#8.2.6`
- bootstrap version `#4.0.0`

### What is happening?
The class names are getting populated.

Styles are not coming out/loading up

The class names should be loaded as per react and i should be able to see the styled components

### Steps to reproduce issue

1. Install preact-cli (https://github.com/developit/preact-cli)
2. Clone the repo https://github.com/vinaybedre/reactstrap-issue , run npm install and hit npm run dev

### Code
Clone the repo https://github.com/vinaybedre/reactstrap-issue

this is an extension of the issue #803

**Comment by TheSharpieOne** [comment]
reactstrap doesn't import scss, something like webpack will do that in conjunction with a loader and node-sass. See https://github.com/webpack-contrib/sass-loader#examples

Since you are using preact-cli, this might help: https://github.com/developit/preact-cli/issues/443

Also, AFAIK you have to use `~` when referencing node_modules packages in scss when using the webpack loader
https://github.com/vinaybedre/reactstrap-issue/blob/bdf8e9b6721b654736f93c97119a9f3a31b48dd8/src/routes/home/style.scss
https://github.com/webpack-contrib/sass-loader#imports

**Comment by virgofx** [comment]
Yeah, I was going to follow up --- This is not a reactstrap issue. This is an issue with your own application setup.
