### ISSUE TITLE
Feature request / Add style prop

### ISSUE THREAD

**Issue by shishiranshuman13** [reactstrap/reactstrap#809]
### Issue description (Feature request)

- Will it be possible to inject the `style` prop for all the components? Since inline styles are used widely I thought It might be a good idea to create an issue.
- I have been using [Radium](https://github.com/FormidableLabs/radium/) to overcome this issue till now, but it's becoming a pain to wrap everything with Radium.

**Comment by TheSharpieOne** [comment]
In react, the style prop is an object and not a string. The object has key-value pairs where the key is the javascript name and not the common css name (such as borderLeft instead of border-left). The values are usually strings (like '100%'), but can be numbers if there is no units (such as for zIndex). Reactstrap components pass all of the extra props you give them down and merges some props if it has to add to them (such as className). Most components are simple, only outputting a single node which makes it simple to add the extra props to. Other components output complex structures which make it hard to be able to add extra props to each of the various nodes being output. 

Have you tried adding a style prop with a style object?
See https://reactjs.org/docs/dom-elements.html#style

**Comment by shishiranshuman13** [comment]
@TheSharpieOne Sorry, my bad. 

I tried passing the style in the Navbar component and it worked. https://codepen.io/anon/pen/xYOewy

I just realized that I have been using [@types/reactstrap](https://www.npmjs.com/package/@types/reactstrap) since my project is written in TypeScript. Might need to add the style prop in the types.

**Comment by shishiranshuman13** [comment]
I'll close the issue here. But I would like to know if the issue to add the `style` prop is to be created here or in the [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) repo?
