### ISSUE TITLE
Change valid prop to invalid in the API of form inputs

### ISSUE THREAD

**Issue by asliwinski** [reactstrap/reactstrap#850]
My suggestion is to change the API of form inputs to support `invalid` prop (instead of or alongside `valid` prop).

What I have to do now when integrating with libraries such as redux-form or formik:

```
<Input 
  type="email"
  name="email"
  id="email"
  placeholder="Email"
  valid={touched.email && errors.email ? false : null}
  onChange={handleChange}
  onBlur={handleBlur}
  value={values.email} />
{touched.email && errors.email && <FormFeedback>{errors.email}</FormFeedback>}
```

What seems to make more sense:

```
<Input 
  type="email"
  name="email"
  id="email"
  placeholder="Email"
  invalid={touched.email && errors.email}
  onChange={handleChange}
  onBlur={handleBlur}
  value={values.email} />
{touched.email && errors.email && <FormFeedback>{errors.email}</FormFeedback>}
```

What do you think?

**Comment by TheSharpieOne** [comment]
I'm not sure what `errors.email` is, but it looks like it might be a string based on the usage inside the `FormFeedback`. `valid` accepts only a boolean (or `undefined`/not provided at all to indicate no validity state).

From what I gather, the issue is that you don't want `valid` to be `true` which will show the input with a "success" outline (with default bootstrap styles) and you want an easier way to do that.
Because the value should be a boolean, I don't think `invalid` _instead of_ `valid` will make much of a difference; only flip the issue. I don't really like having two boolean props which are just opposites, but it would be more explicit (which isn't a bad thing) and there are really three state (though I figured `true`/`false`/`undefined` would handle that.)
We probably wouldn't accept a string, only a boolean for the value as it makes sense and is more explicit, but because they are separate, `false` in either prop will not trigger a different class to be applied (only `true` would do anything). It's easy enough to get a boolean out of other values (such as `invalid={!!errors.email}`). Even if you didn't pass a boolean, it would only complain during development, those checks are gone in prod. It would end up using truthy/falsey to determine if the class gets applied.

**Comment by asliwinski** [comment]
> I'm not sure what errors.email is, but it looks like it might be a string

Yes, it's a string with the error message which is defined (or not) after validation function runs.

> From what I gather, the issue is that you don't want valid to be true which will show the input with a "success" outline (with default bootstrap styles) and you want an easier way to do that.

That's my point exactly.

The use of `errors` object seems to be the common practice across form libraries, and using `invalid` prop would allow for a more direct transfer of the error state, without the need for this weird ternary expression.

`invalid={!!errors.email}` still looks better to me than `invalid={errors.email ? false : null}`
