### ISSUE TITLE
Input elements shouldn't have children

### ISSUE THREAD

**Issue by jhsware** [reactstrap/reactstrap#871]
https://github.com/reactstrap/reactstrap/blob/0648cc2c24a5dd55f93892df9c6c9d144338f670/src/__tests__/Input.spec.js#L60

**Comment by TheSharpieOne** [comment]
They should when the "input" is a `<select>` or  `<textarea>`, which the `Input` can render given `type="select"` or `type="textarea"` respectfully.

**Comment by jhsware** [comment]
The default input type is `text` so the test should be something like this: `<Input type="select">Yo!</Input>`

Are you sure `type="textarea"` is allowed children? The React-clone Inferno.js complains if textarea has children.

**Comment by TheSharpieOne** [comment]
Sounds like a defect for inferno. `<textarea>` is not a void element, it allows content within it. See: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea

Yes, the test itself probably could use `type="textarea"`, but we don't check the type to determine if it can have children (we probably should, it would be simple since we use the type to determine the `tag` and if the `tag` is input, we should not allow children).

**Comment by jhsware** [comment]
React doesn't follow HTML-specs in that regard: https://reactjs.org/docs/forms.html

```
<textarea value={this.state.value} onChange={this.handleChange} />
```

Only `<select>` should have children from what I can tell.

**Comment by TheSharpieOne** [comment]
Yeah, looks like they are removing the ability for `<textarea>`s to have children in react 17: https://github.com/facebook/react/pull/11639

**Comment by jhsware** [comment]
I have made a port of Reactstrap to Inferno.js so I get stuck in the middle at times... :D
