### ISSUE TITLE
Property 'src' does not exist

### ISSUE THREAD

**Issue by jesperlandmer** [reactstrap/reactstrap#891]
### Issue description

- components: "Media"
- reactstrap version "^5.0.0-beta.2"
- react version "^16.2.0"
- bootstrap version "^4.0.0"

### What is happening?

Using the Media component and want to import an image from a url. Using "data-src" doesn't provide any image, but using "src" does. For some reason I'm getting an error for using "src"

### What should be happening?

Should compile without errors

### Steps to reproduce issue

```
        <Media>
          <Media left href="#">
            <Media object src={this.state.image} /> // e.g. https://example.img.com
          </Media>
          <Media body>
             Stuff
          </Media>
        </Media>
```

### Error message in console

```
ERROR in [at-loader] ./src/views/Dashboard/Feed.tsx:77:27
    TS2339: Property 'src' does not exist on type 'IntrinsicAttributes & MediaProps & { children?: ReactNode; }'.
```

**Comment by TheSharpieOne** [comment]
Seems like a typescript issue. You should probably open an issue in the repo you are getting your typings from. reactstrap doesn't officially have it support them, but the community has made some and they are managed in that repo (sorry, I'm on mobile and cannot get a link quickly).

Typings don't make too much sense with reactstrap since reactstrap just passes any extra props through, meaning the allowed/accepted props are really any. Sure reactstrap explicitly uses a few, but in cases like this or when the tag prop is used it is impossible to explicitly dictate which props are allowed.
