### ISSUE TITLE
Dropdown not working inside Array.map()

### ISSUE THREAD

**Issue by Samrat-Saha-Sammy** [reactstrap/reactstrap#892]
Exact same component is working outside the loop but not working inside the Array.map function, as required to loop through a list of drop-down array.

- components: `Dropdown`
- reactstrap version `#5.0.0-beta`
- import method `es` 
- react version `#16.2.0`
- bootstrap version `#4.0.0`

### What is happening?

I have a array of data that generates a new dropdown via looping but the dropdown is not working inside the loop but if I cut paste the code snippet outside the loop the dropdown stops working. It Displays the button but nothing happens when clicked. 

### What should be happening?

It should display the other options in the dropdown list. 

### Error message in console

```
No Error in Console. 
```

**Comment by TheSharpieOne** [comment]
You have to manage the state (isOpen) for each of the dropdowns, you'd also have to have a callback (toggle) for each one to individually toggle each one.
If you don't want to do that, you can use an uncontrolled dropdown as explained at the bottom of the docs.

**Comment by Samrat-Saha-Sammy** [comment]
@TheSharpieOne 

I am managing both the isOpen & callback repeatedly.

`<Dropdown isOpen={this.state.isOpened[rowIndex]} toggle={ ()=> {()=> this.xtoggle(0)} }>
    <DropdownToggle caret className="btn-warning btn-sm">
        {cell.val}
    </DropdownToggle>
    <DropdownMenu>
    {
        template['options'].map((row, index) => {
        return (
                <DropdownItem>{row}</DropdownItem>
            )
        })
    }
    </DropdownMenu>
</Dropdown>`

**Comment by TheSharpieOne** [comment]
Your toggle callback does nothing. It defines a new function which, when ran creates another new function and returns nothing. `this.toggle` would never get called.

**Comment by Samrat-Saha-Sammy** [comment]
Should it be returning something or it should just change the state of the individual drowndown **isOpen**  states. The toggle function is called and also changing the state perfectly but somehow the list is not displaying. no error in console.

**Comment by TheSharpieOne** [comment]
Take a look at this: https://stackblitz.com/edit/reactstrap-v5beta-z5nhvf?file=Example.js
Notice how the first group of dropdowns does what you are seeing, and that `this.toggle` never gets called. The second group works and `this.toggle` gets called. The last group also works, but it uses `UncontrolledDropdown`s so that you don't need to have a toggle method or manage the state yourself.

**Comment by Samrat-Saha-Sammy** [comment]
@TheSharpieOne  Thanks for the Answer. Really appreciate your effort to prove the correct scenarios. Awesome Help Buddy. 

I last question how to handle the individual dropdown change inside `<UncontrolledDropdown>`

**Comment by TheSharpieOne** [comment]
`UncontrolledDropdown` works the same way as `Dropdown` you just don't provide the `isOpen` and `toggle` props. If you need either one of those (to gain more control), you'll have to use `Dropdown` directly.
Dropdowns don't really "change", they are not like `<select>`, they don't have a value. They are primarily for displaying lists of links and such as noted by bootstrap:
>Dropdowns are toggleable, contextual overlays for displaying lists of links and more

Because of that, there is no nice way to determine which item was selected. (the same goes for bootstrap.js itself)
If you need to determine which item was selected to take action, you can add individual event listeners on the items to determine which one is being clicked.
Or Dropdown's toggle callback should be passed the event which triggered it, which you can use to determine which item was selected (if any) to trigger the toggle (it's more advanced)

**Comment by Samrat-Saha-Sammy** [comment]
@TheSharpieOne  Thanks for the Prompt response. I think **Dropdown** should have a onChange callback with the id of the selected option. It a more realistic scenarios to implement a dropdown. 

It The addon callback will really help a lot other writing a lot of code in developer side.
