### ISSUE TITLE
Bug prone example in Dropdowns documentation

### ISSUE THREAD

**Issue by mparulski** [reactstrap/reactstrap#954]
I have found in Dropdowns documentation (https://reactstrap.github.io/components/dropdowns/) example which could be bug prone. toggle() function uses actual "this.state" but sholud use "prevState":
```
toggle() {
    this.setState({
      dropdownOpen: !this.state.dropdownOpen
    });
  }
```
should be 
```
toggle() {
this.setState(prevState => ({
      dropdownOpen: !prevState.dropdownOpen
    }));
}
```
as it is in reactjs documentation (https://reactjs.org/docs/handling-events.html)

**Comment by TheSharpieOne** [comment]
It's debounced so that if the user clicks it multiple times (like twice) before it renders, it will toggle it once.

**Comment by mparulski** [comment]
I haven't seen the debounced effect in my tests when I used 
```
this.setState(prevState => ({
      dropdownOpen: !prevState.dropdownOpen
    }));
```

**Comment by TheSharpieOne** [comment]
right, with the functional setState, you don't get the debounce effect; each time the function is called it has the most recent prevState.
With the object setState, each time it is called before reconciliation, `this.state` will be the same, and thus result in the same state.
It's a quirk which can be removed since it's just an example and most people will never experience either case. Most of the example for functional setState are around counters, where data is not a boolean so you don't want to debounce the state or else you will "miss" data

**Comment by mparulski** [comment]
Thank you for your help.

**Comment by GoPro16** [comment]
Closing this as docs have been updated to hooks with proper setter.
