### ISSUE TITLE
Question: Active Link Highlight

### ISSUE THREAD

**Issue by ThomasJT** [reactstrap/reactstrap#957]
Hello

How can I highlight a link that has been clicked. For example the supersimple code below will highlight link named 'about' in blue, for a second, after which it flickers back to normal navbar. Albeit I been able to in many ways custom style your navbar I can not for all the tea in the world figure out how to highlight an active link and keep it highlighted. For your info, I am using BrowserRouter, but not sure if that has any relevance...

Simple code (the blue highlight flickers when you click but then navbar link goes back to normal look and feel)

```
export default class Example extends React.Component {
  constructor(props) {
    super(props);

    this.toggle = this.toggle.bind(this);
    this.state = {
      isOpen: false,
    };
  }

  toggle() {
    this.setState({
      isOpen: !this.state.isOpen
    });
  }

  onClick() {
    this.setState({
      bgColor:'blue'
    })
  }

  render() {

    return (
      <Navbar color="light" light expand="sm">
        <NavbarBrand href="/">BLEBB BLEBB</NavbarBrand>
        <NavbarToggler onClick={this.toggle}/>
        <Collapse isOpen={this.state.isOpen} navbar>
          <Nav className="ml-auto" navbar>
            <NavItem className="navLink">
              <NavLink href="/" onClick={this.onClick.bind(this)} style={{backgroundColor:this.state.bgColor}}>About</NavLink>
            </NavItem>
            <NavItem className="navLink">
              <NavLink href="/work">Work</NavLink>
            </NavItem>
            <NavItem className="navLink">
              <NavLink href="/contact">Contact</NavLink>
            </NavItem>
          </Nav>
        </Collapse>
      </Navbar>
    );
  }
```

Thanks in Advance, fellow tea drinkers

**Comment by TheSharpieOne** [comment]
You can use Link from react route dom and set that as the `tag` prop. It has a prop called `activeClassName` which you can set to "active" (per bootstrap or whatever custom className you want). When that route is active, that class will be applied. You also want to change `href` to `to` per react router
As an example, take a look at the code for the docs navigation
https://github.com/reactstrap/reactstrap/blob/master/docs/lib/UI/Nav.js

**Comment by TheSharpieOne** [comment]
I forgot the docs have some very out-dated dependences. The older version of react-router used `Link`, the newer version uses `NavLink` (the name collides with the one from reactstrap so you have to rename it at the import like you did)

The `tag` prop is supported by every component. It allows you to override the element/tag/component in which the reactstrap component renders. For instance, reactstrap's `Card` renders a `<div>` element, but if you wanted it to render a `<main>` element (for more semantic markup), you can pass `tag="main"`. It also works with other components, allowing you to pass a react component to `tag` and it will be used (as you did above).
To me, it's easier to understand by looking at the code:
We default the tag to what bootstrap typically uses (in the case of NavLink, it's an anchor tag (`a`)):
https://github.com/reactstrap/reactstrap/blob/210b53f57f135d7f7ea28ec1fe87966e211e76c6/src/NavLink.js#L17-L19
We rename `tag` to `Tag` so that it starts with a capital letter so JSX can parse it (see [how babel transpiles it](http://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=MYewdgzgLgBArgBwQUwE7AIYWTAvDAHgBUMBzGAegD5KLCBaGMEKAS2B1agHIIYMYANwypWGAEYAbZAChQkWJJAB3NJmx5CUMpRoU6BRszYcYXXvxjRRYUkA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&lineWrap=false&presets=latest%2Creact%2Cstage-2&prettier=false&targets=&version=6.26.0&envVersion=))
https://github.com/reactstrap/reactstrap/blob/210b53f57f135d7f7ea28ec1fe87966e211e76c6/src/NavLink.js#L48
Then we just put that variable into JSX, similar to how you would use an imported component via variable reference. Notice we pass all of the additional props you provide, so things like `to` and `activeClassName` make their way to the underlying component which gets rendered.
https://github.com/reactstrap/reactstrap/blob/210b53f57f135d7f7ea28ec1fe87966e211e76c6/src/NavLink.js#L63

**Comment by ThomasJT** [comment]
That makes sense thanks for explaining. Just one small question. With eact path I have managed to make the about link highlight only when about is clicked matching that path exactly and that path is "/" (since about is my "home" page in other name.

But when landing on localhost, about is not highlighted until I click on it, what could be the best way to amend that? Maybe this question falls beyond the scope of what I was asking before

**Comment by ThomasJT** [comment]
Ignore it works, closing and sleeping!

**Comment by ThomasJT** [comment]
Thanks, got it all working now! Moving on!

**Comment by Luckyshroom** [comment]
Thanks)

**Comment by softmixt** [comment]
I think you can easily use this :
`              <NavLink href="/work" active={window.location === '/work'}>Work</NavLink>
`

**Comment by AbProgr** [comment]
I had the `exact prop in react-router 4.3.1 route` but also needed to add `exact to reactstrap 7.0.2 NavLink` to prevent base route from being shown as active at all other child routes.
https://github.com/reactstrap/reactstrap/issues/336#issuecomment-453724969

**Comment by NoftScarlet** [comment]
Had this question today and my solution is a bit different. I did not use react-router-dom, instead I used `classnames` ([repo](https://github.com/JedWatson/classnames)) and the active state of `NavLink`:

`<NavLink onClick={e => this.changeActiveIndex(e, "activeIndex", my.item.id) } className = { classnames ({"class-1": this.state.activeIndex === my.item.id ? true : false,  "class-2":true })} href="#" >
  "Link Text"
</NavLink>`

`onClick` sets the current active NavLink index (a state) by calling a function `changeActiveIndex`. 
`"class-1"` is added to NavLink whenever the link is active, and is removed otherwise. I personally use the class `"btn-info"` for my project.
`"class-2"` is always added to NavLink because the condition is always `true`.

**Comment by slegaitis** [comment]
No need to reinvent the wheel :) Use simple css attribute selectors:

```
.nav-link[aria-current="page"] {
    color: #000;
    opacity: 1;
    // Other styles
}
```

**Comment by khwerhahn** [comment]
Is there a good way to set a default route? In my case the URL is already `/instruments/123`. Let's say I wanted the /charts to be the default route if nothing is passed after the `/instruments/123`

```
let { path, url } = useRouteMatch();

<div>
    <Nav tabs>
        <NavItem>
            <NavLink tag={RRNavLink} to={`${url}/chart`} activeClassName="active">Chart</NavLink>
        </NavItem>
        <NavItem>
            <NavLink tag={RRNavLink} to={`${url}/news`} activeClassName="active">News</NavLink>
        </NavItem>
        <NavItem>
            <NavLink tag={RRNavLink} to={`${url}/company`} activeClassName="active">Company</NavLink>
        </NavItem>
        <NavItem>
            <NavLink tag={RRNavLink} to={`${url}/kpis`} activeClassName="active">KPIs</NavLink>
        </NavItem>
    </Nav>
</div>
```
