### ISSUE TITLE
jquery needed?

### ISSUE THREAD

**Issue by ggmartins** [reactstrap/reactstrap#970]
### Issue description

- components: `reactstrap`
- reactstrap version `#5.0.0`
- import method `no idea` (if umd, are you using the "full" version (only for v5+)?)
- react version `#16.3.2`
- bootstrap version `#4.1.0`

### What is happening?

Sorry, I've just started with react + reactstrap. What should I do if we install bootstrap (npm i -S bootstrap) and get the message:
_bootstrap@4.1.0 requires a peer of jquery@1.9.1 - 3 but none is installed_

Should we go ahead and install jquery? or it will conflict with reactstrap/react ?

Thanks in advance

**Comment by TheSharpieOne** [comment]
You can safely ignore that peer dependency, or you can install it and just not use or reference jquery anywhere.
jquery is only a dependency for bootstrap when using bootstrap.js, but since you are using reactstrap, you don't need bootstrap.js nor jquery.
I believe I have read somewhere that in the future bootstrap may split up the styles from the functionality (javascript) so that you can import just the styles and use a third-party, library specific implementation (such as reactstrap)

**Comment by TheSharpieOne** [comment]
I believe ajv and ajv-keywords are required by webpack. Are you using webpack?

**Comment by aldrinpvincent** [comment]
Yes, I'm using webpack. I used create-react-app for the initial template, so webpack is there.
Thanks for the reply.

**Comment by aldrinpvincent** [comment]
seems like ajv is already there with create-react-app, no need to add separately

**Comment by TheSharpieOne** [comment]
depending on your packages and how npm structures your node_modules, you may need to explicitly add it.
