### ISSUE TITLE
When I try to use styled component to style reactstrap component, I am keep getting similar error like following. What is the solution?

### ISSUE THREAD

**Issue by adamchenwei** [reactstrap/reactstrap#989]
### Issue description

- components: `name`
- reactstrap version `latest`
- import method `umd/csj/es` (if umd, are you using the "full" version (only for v5+)?)
- react version `#16.0`
- bootstrap version `#4.x`

### What is happening?

throw warning for functionality apply correctly, like below:
<img width="694" alt="screen shot 2018-04-30 at 10 14 16 am" src="https://user-images.githubusercontent.com/4201698/39431624-4bcc58d6-4c5f-11e8-9b2e-963e02098783.png">

### What should be happening?

it shouldn't throw warning.

### Steps to reproduce issue

1. build the component with attribute with CAMEL case
2. refresh the browser, when load component observe error

### Error message in console
*note that it happens all the time as long as I tried to apply styled component above a reactstrap component to extend its styles
```
index.js:131 Warning: React does not recognize the `hasBorderRight` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `hasborderright` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in div (created by Col)
    in Col (created by ColCenterAll)
    in ColCenterAll (created by StyledColCenterAll)
    in StyledColCenterAll (created by CreativePanelGroupCard)
    in div (created by Row)
    in Row (created by CreativePanelGroupCard)
    in section (created by ComponentContainer)
    in ComponentContainer (created by Container)
    in Container (created by CreativePanelGroupCard)
    in CreativePanelGroupCard
    in section (created by PaddedDemoSpace)
    in PaddedDemoSpace
```

### Code

```js
export default styled(Col)`
  padding: 8px;
  ${props => (props.hasBorderRight ? `
    border-right-color: ${grey3};
    border-right-width: 1px;
    border-right-style: solid;
  ` : null)}
`;
```

**Comment by TheSharpieOne** [comment]
This issue is probably best taken up with react itself as it is what is throwing the warning given what you expect should happen is: "it shouldn't throw warning." 
Or you can try not setting the prop in which react is complaining about since that is not a reactstrap prop, you shouldn't be setting it on a reactstrap component: `hasBorderRight`
Or you can open up an issue with the styled component library omit props (it looks like you can currently add additional props, but not omit ones: https://www.styled-components.com/docs/basics#attaching-additional-props maybe setting it to undefined in the .attr will work? idk, best to ask that library since it is a systemic issue with styled component)

**Comment by adamchenwei** [comment]
@TheSharpieOne is there way I can strip some of the props off right before other component start passing props into reactstrap's component? or maybe a way to disable warning? Thanks!

**Comment by TheSharpieOne** [comment]
That question is best asked at https://github.com/styled-components/styled-components the reactstrap answer is to just not pass the prop if you don't want it.

**Comment by adamchenwei** [comment]
@TheSharpieOne but it's not about removing.... Ok so I guess it's more of style component realm. But it can be great if we can disable this alert?

**Comment by TheSharpieOne** [comment]
reactstrap doesn't add the warning/alert, it cannot remove the warning/alert. The warning/alert is added by react itself. There is nothing reactstrap can do.
See: https://github.com/facebook/react/blob/4c3470eef832d64e03d18c19a70f2501f9becbfd/packages/react-dom/src/shared/ReactDOMUnknownPropertyHook.js#L175-L191

**Comment by adamchenwei** [comment]
@TheSharpieOne so I guess, for now, what would be the recommended way to extend style for reactstrap components atm?

**Comment by TheSharpieOne** [comment]
the `style` prop for inline styles and/or the `classNames` prop for CSS. These are standard react props and are not specific to reactstrap.

**Comment by dosentmatter** [comment]
I'm having the same problem. But styled-components does strip off props if it knows what the underlying DOM element is. For example, here's me using `styled.img`. I pass custom props `onPrimaryClick` and `onSecondaryClick`. If you look at the `img` tag below it, you will see that it doesn't have those two props as attributes. This is because styled-components know that it's an `img`, so it strips off props that don't belong.
![image](https://user-images.githubusercontent.com/5732253/39714911-5e63be04-51e0-11e8-99c2-17ca26b9e53c.png)

Here's a second example using styled-components with reactstrap. I get the same error as @adamchenwei. You can see my custom prop `borderColorRed`. Notice that it gets passed through to the reactstrap `Button` and finally to the DOM `button`. This is because styled-components doesn't know that it ends up being a DOM `button` (since it's just wrapping a reactstrap component). So it doesn't omit the props. reactstrap assumes you know what you are doing with the props and just passes it down to the DOM `button`.
![image](https://user-images.githubusercontent.com/5732253/39715060-d5b18fc2-51e0-11e8-8fe3-8e8e09105192.png)

I need to figure out a way to consume those props after it gets to the styled-component but before it gets to reactstrap and then the DOM `button`. Maybe by wrapping the reactstrap `Button` in a higher order component. Or maybe styled-components provides something for me to do this easily.

**Comment by TheSharpieOne** [comment]
https://github.com/styled-components/styled-components/issues/305#issuecomment-266197867 has a suggestion, but it looks like styled-components is still trying to determine a solution to this issue: https://github.com/styled-components/styled-components/issues/439

**Comment by TheSharpieOne** [comment]
Can't borrow anything from that because they are different implementation. Reactstrap uses bootstrap's CSS just as bootstrap does only recreating the javascript functionality so that it is not jquery making DOM manipulations. styles-bootstrap basically recreates bootstrap entirely, yes that's right, it defines all of the styles and doesn't actually use bootstrap's css or styles.

There are advantages to disadvantages to both. With reactstrap, you have to use bootstrap's css which may mean pulling in unused styles, but you can create a custom build of bootstrap css (per their docs) to only include the component styles you need. Using themes is just as its always been with bootstrap and you can use the same theme across multiple sites with various frameworks and libraries because it's all just css. With styled components, you get only the styles you need out of the box, but now applying a theme doesn't follow bootstrap's docs and is specific to the library you used. Also that theme you made specifically for the styled component library only works for that library. This may not be a big deal, but for companies which have various sites written in various language using various libraries, making a change to 1 css project to provide a theme usable by all of them is a must. Brad frost has some good articles on technology agnostic style guides and implementation.
